<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/api_shop.php');
	include_once(__DIR__ . '/api_shop_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('api_shop');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'api_shop';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`api_shop`.`id`" => "id",
		"`api_shop`.`app_id`" => "app_id",
		"`api_shop`.`like_charge`" => "like_charge",
		"`api_shop`.`follow_charge`" => "follow_charge",
		"`api_shop`.`tweet_charge`" => "tweet_charge",
		"`api_shop`.`max_user`" => "max_user",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`api_shop`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`api_shop`.`id`" => "id",
		"`api_shop`.`app_id`" => "app_id",
		"`api_shop`.`like_charge`" => "like_charge",
		"`api_shop`.`follow_charge`" => "follow_charge",
		"`api_shop`.`tweet_charge`" => "tweet_charge",
		"`api_shop`.`max_user`" => "max_user",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`api_shop`.`id`" => "Id",
		"`api_shop`.`app_id`" => "App_id",
		"`api_shop`.`like_charge`" => "Like_charge",
		"`api_shop`.`follow_charge`" => "Follow_charge",
		"`api_shop`.`tweet_charge`" => "Tweet_charge",
		"`api_shop`.`max_user`" => "Max_user",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`api_shop`.`id`" => "id",
		"`api_shop`.`app_id`" => "app_id",
		"`api_shop`.`like_charge`" => "like_charge",
		"`api_shop`.`follow_charge`" => "follow_charge",
		"`api_shop`.`tweet_charge`" => "tweet_charge",
		"`api_shop`.`max_user`" => "max_user",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`api_shop` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'api_shop_view.php';
	$x->TableTitle = 'Api_shop';
	$x->TableIcon = 'resources/table_icons/shopping.png';
	$x->PrimaryKey = '`api_shop`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'App_id', 'Like_charge', 'Follow_charge', 'Tweet_charge', 'Max_user', ];
	$x->ColFieldName = ['id', 'app_id', 'like_charge', 'follow_charge', 'tweet_charge', 'max_user', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/api_shop_templateTV.html';
	$x->SelectedTemplate = 'templates/api_shop_templateTVS.html';
	$x->TemplateDV = 'templates/api_shop_templateDV.html';
	$x->TemplateDVP = 'templates/api_shop_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: api_shop_init
	$render = true;
	if(function_exists('api_shop_init')) {
		$args = [];
		$render = api_shop_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: api_shop_header
	$headerCode = '';
	if(function_exists('api_shop_header')) {
		$args = [];
		$headerCode = api_shop_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: api_shop_footer
	$footerCode = '';
	if(function_exists('api_shop_footer')) {
		$args = [];
		$footerCode = api_shop_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
