<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/auto_dm.php');
	include_once(__DIR__ . '/auto_dm_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('auto_dm');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'auto_dm';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`auto_dm`.`id`" => "id",
		"`auto_dm`.`user_id`" => "user_id",
		"`auto_dm`.`message`" => "message",
		"`auto_dm`.`time`" => "time",
		"`auto_dm`.`status`" => "status",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`auto_dm`.`id`',
		2 => '`auto_dm`.`user_id`',
		3 => 3,
		4 => '`auto_dm`.`time`',
		5 => '`auto_dm`.`status`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`auto_dm`.`id`" => "id",
		"`auto_dm`.`user_id`" => "user_id",
		"`auto_dm`.`message`" => "message",
		"`auto_dm`.`time`" => "time",
		"`auto_dm`.`status`" => "status",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`auto_dm`.`id`" => "Id",
		"`auto_dm`.`user_id`" => "User_id",
		"`auto_dm`.`message`" => "Message",
		"`auto_dm`.`time`" => "Time",
		"`auto_dm`.`status`" => "Status",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`auto_dm`.`id`" => "id",
		"`auto_dm`.`user_id`" => "user_id",
		"`auto_dm`.`message`" => "message",
		"`auto_dm`.`time`" => "time",
		"`auto_dm`.`status`" => "status",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`auto_dm` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'auto_dm_view.php';
	$x->TableTitle = 'Auto_dm';
	$x->TableIcon = 'resources/table_icons/text.png';
	$x->PrimaryKey = '`auto_dm`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'User_id', 'Message', 'Time', 'Status', ];
	$x->ColFieldName = ['id', 'user_id', 'message', 'time', 'status', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/auto_dm_templateTV.html';
	$x->SelectedTemplate = 'templates/auto_dm_templateTVS.html';
	$x->TemplateDV = 'templates/auto_dm_templateDV.html';
	$x->TemplateDVP = 'templates/auto_dm_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: auto_dm_init
	$render = true;
	if(function_exists('auto_dm_init')) {
		$args = [];
		$render = auto_dm_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: auto_dm_header
	$headerCode = '';
	if(function_exists('auto_dm_header')) {
		$args = [];
		$headerCode = auto_dm_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: auto_dm_footer
	$footerCode = '';
	if(function_exists('auto_dm_footer')) {
		$args = [];
		$footerCode = auto_dm_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
