<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/automation_subs.php');
	include_once(__DIR__ . '/automation_subs_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('automation_subs');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'automation_subs';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`automation_subs`.`id`" => "id",
		"`automation_subs`.`user_id`" => "user_id",
		"`automation_subs`.`script_id`" => "script_id",
		"`automation_subs`.`status`" => "status",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`automation_subs`.`id`',
		2 => 2,
		3 => 3,
		4 => '`automation_subs`.`status`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`automation_subs`.`id`" => "id",
		"`automation_subs`.`user_id`" => "user_id",
		"`automation_subs`.`script_id`" => "script_id",
		"`automation_subs`.`status`" => "status",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`automation_subs`.`id`" => "Id",
		"`automation_subs`.`user_id`" => "User_id",
		"`automation_subs`.`script_id`" => "Script_id",
		"`automation_subs`.`status`" => "Status",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`automation_subs`.`id`" => "id",
		"`automation_subs`.`user_id`" => "user_id",
		"`automation_subs`.`script_id`" => "script_id",
		"`automation_subs`.`status`" => "status",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`automation_subs` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'automation_subs_view.php';
	$x->TableTitle = 'Automation_subs';
	$x->TableIcon = 'resources/table_icons/account_balances.png';
	$x->PrimaryKey = '`automation_subs`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'User_id', 'Script_id', 'Status', ];
	$x->ColFieldName = ['id', 'user_id', 'script_id', 'status', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/automation_subs_templateTV.html';
	$x->SelectedTemplate = 'templates/automation_subs_templateTVS.html';
	$x->TemplateDV = 'templates/automation_subs_templateDV.html';
	$x->TemplateDVP = 'templates/automation_subs_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: automation_subs_init
	$render = true;
	if(function_exists('automation_subs_init')) {
		$args = [];
		$render = automation_subs_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: automation_subs_header
	$headerCode = '';
	if(function_exists('automation_subs_header')) {
		$args = [];
		$headerCode = automation_subs_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: automation_subs_footer
	$footerCode = '';
	if(function_exists('automation_subs_footer')) {
		$args = [];
		$footerCode = automation_subs_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
