<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/automation_scripts.php');
	include_once(__DIR__ . '/automation_scripts_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('automation_scripts');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'automation_scripts';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`automation_scripts`.`id`" => "id",
		"`automation_scripts`.`logo`" => "logo",
		"`automation_scripts`.`file_path`" => "file_path",
		"`automation_scripts`.`execution`" => "execution",
		"`automation_scripts`.`automation`" => "automation",
		"`automation_scripts`.`category`" => "category",
		"`automation_scripts`.`title`" => "title",
		"`automation_scripts`.`description`" => "description",
		"`automation_scripts`.`author`" => "author",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`automation_scripts`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`automation_scripts`.`automation`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`automation_scripts`.`id`" => "id",
		"`automation_scripts`.`logo`" => "logo",
		"`automation_scripts`.`file_path`" => "file_path",
		"`automation_scripts`.`execution`" => "execution",
		"`automation_scripts`.`automation`" => "automation",
		"`automation_scripts`.`category`" => "category",
		"`automation_scripts`.`title`" => "title",
		"`automation_scripts`.`description`" => "description",
		"`automation_scripts`.`author`" => "author",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`automation_scripts`.`id`" => "Id",
		"`automation_scripts`.`logo`" => "Logo",
		"`automation_scripts`.`file_path`" => "File_path",
		"`automation_scripts`.`execution`" => "Execution",
		"`automation_scripts`.`automation`" => "Automation",
		"`automation_scripts`.`category`" => "Category",
		"`automation_scripts`.`title`" => "Title",
		"`automation_scripts`.`description`" => "Description",
		"`automation_scripts`.`author`" => "Author",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`automation_scripts`.`id`" => "id",
		"`automation_scripts`.`logo`" => "logo",
		"`automation_scripts`.`file_path`" => "file_path",
		"`automation_scripts`.`execution`" => "execution",
		"`automation_scripts`.`automation`" => "automation",
		"`automation_scripts`.`category`" => "category",
		"`automation_scripts`.`title`" => "title",
		"`automation_scripts`.`description`" => "description",
		"`automation_scripts`.`author`" => "author",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`automation_scripts` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'automation_scripts_view.php';
	$x->TableTitle = 'Automation_scripts';
	$x->TableIcon = 'resources/table_icons/application_cascade.png';
	$x->PrimaryKey = '`automation_scripts`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Logo', 'File_path', 'Execution', 'Automation', 'Category', 'Title', 'Description', 'Author', ];
	$x->ColFieldName = ['id', 'logo', 'file_path', 'execution', 'automation', 'category', 'title', 'description', 'author', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/automation_scripts_templateTV.html';
	$x->SelectedTemplate = 'templates/automation_scripts_templateTVS.html';
	$x->TemplateDV = 'templates/automation_scripts_templateDV.html';
	$x->TemplateDVP = 'templates/automation_scripts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: automation_scripts_init
	$render = true;
	if(function_exists('automation_scripts_init')) {
		$args = [];
		$render = automation_scripts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: automation_scripts_header
	$headerCode = '';
	if(function_exists('automation_scripts_header')) {
		$args = [];
		$headerCode = automation_scripts_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: automation_scripts_footer
	$footerCode = '';
	if(function_exists('automation_scripts_footer')) {
		$args = [];
		$footerCode = automation_scripts_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
