<?php

// Data functions (insert, update, delete, form) for table billing

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function billing_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('billing');
	if(!$arrPerm['insert']) return false;

	$data = [
		'user_id' => Request::lookup('user_id', ''),
		'name' => Request::val('name', ''),
		'email' => Request::val('email', ''),
		'phone_number' => Request::val('phone_number', ''),
		'tx_ref' => Request::val('tx_ref', ''),
		'charged_amount' => Request::val('charged_amount', ''),
		'payment_type' => Request::val('payment_type', ''),
		'created_at' => Request::val('created_at', ''),
		'auth_model' => Request::val('auth_model', ''),
		'device_fingerprint' => Request::val('device_fingerprint', ''),
		'flw_ref' => Request::val('flw_ref', ''),
		'account_id' => Request::val('account_id', ''),
		'amount_settled' => Request::val('amount_settled', ''),
		'app_fee' => Request::val('app_fee', ''),
		'status' => Request::val('status', ''),
	];


	// hook: billing_before_insert
	if(function_exists('billing_before_insert')) {
		$args = [];
		if(!billing_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('billing', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('billing', $recID, calculated_fields()['billing']);

	// hook: billing_after_insert
	if(function_exists('billing_after_insert')) {
		$res = sql("SELECT * FROM `billing` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!billing_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('billing', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) billing_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function billing_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function billing_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('billing', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: billing_before_delete
	if(function_exists('billing_before_delete')) {
		$args = [];
		if(!billing_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `billing` WHERE `id`='{$selected_id}'", $eo);

	// hook: billing_after_delete
	if(function_exists('billing_after_delete')) {
		$args = [];
		billing_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='billing' AND `pkValue`='{$selected_id}'", $eo);
}

function billing_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('billing', $selected_id, 'edit')) return false;

	$data = [
		'user_id' => Request::lookup('user_id', ''),
		'name' => Request::val('name', ''),
		'email' => Request::val('email', ''),
		'phone_number' => Request::val('phone_number', ''),
		'tx_ref' => Request::val('tx_ref', ''),
		'charged_amount' => Request::val('charged_amount', ''),
		'payment_type' => Request::val('payment_type', ''),
		'created_at' => Request::val('created_at', ''),
		'auth_model' => Request::val('auth_model', ''),
		'device_fingerprint' => Request::val('device_fingerprint', ''),
		'flw_ref' => Request::val('flw_ref', ''),
		'account_id' => Request::val('account_id', ''),
		'amount_settled' => Request::val('amount_settled', ''),
		'app_fee' => Request::val('app_fee', ''),
		'status' => Request::val('status', ''),
	];

	// get existing values
	$old_data = getRecord('billing', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: billing_before_update
	if(function_exists('billing_before_update')) {
		$args = ['old_data' => $old_data];
		if(!billing_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'billing', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="billing_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('billing', $data['selectedID'], calculated_fields()['billing']);

	// hook: billing_after_update
	if(function_exists('billing_after_update')) {
		$res = sql("SELECT * FROM `billing` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!billing_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='billing' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function billing_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('billing');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_user_id = Request::val('filterer_user_id');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: user_id
	$combo_user_id = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='billing' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='billing' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `billing` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'billing_view.php', false);
		}
		$combo_user_id->SelectedData = $row['user_id'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_user_id->SelectedData = $filterer_user_id;
	}
	$combo_user_id->HTML = '<span id="user_id-container' . $rnd1 . '"></span><input type="hidden" name="user_id" id="user_id' . $rnd1 . '" value="' . html_attr($combo_user_id->SelectedData) . '">';
	$combo_user_id->MatchText = '<span id="user_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="user_id" id="user_id' . $rnd1 . '" value="' . html_attr($combo_user_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_user_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['user_id'] : htmlspecialchars($filterer_user_id, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(user_id_reload__RAND__) == 'function') user_id_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function user_id_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#user_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_user_id__RAND__.value, t: 'billing', f: 'user_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="user_id"]').val(resp.results[0].id);
							$j('[id=user_id-container-readonly__RAND__]').html('<span class="match-text" id="user_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=users_view_parent]').hide(); } else { $j('.btn[id=users_view_parent]').show(); }


							if(typeof(user_id_update_autofills__RAND__) == 'function') user_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'billing', f: 'user_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_user_id__RAND__.value = e.added.id;
				AppGini.current_user_id__RAND__.text = e.added.text;
				$j('[name="user_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=users_view_parent]').hide(); } else { $j('.btn[id=users_view_parent]').show(); }


				if(typeof(user_id_update_autofills__RAND__) == 'function') user_id_update_autofills__RAND__();
			});

			if(!$j("#user_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_user_id__RAND__.value, t: 'billing', f: 'user_id' },
					success: function(resp) {
						$j('[name="user_id"]').val(resp.results[0].id);
						$j('[id=user_id-container-readonly__RAND__]').html('<span class="match-text" id="user_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=users_view_parent]').hide(); } else { $j('.btn[id=users_view_parent]').show(); }

						if(typeof(user_id_update_autofills__RAND__) == 'function') user_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_user_id__RAND__.value, t: 'billing', f: 'user_id' },
				success: function(resp) {
					$j('[id=user_id-container__RAND__], [id=user_id-container-readonly__RAND__]').html('<span class="match-text" id="user_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=users_view_parent]').hide(); } else { $j('.btn[id=users_view_parent]').show(); }

					if(typeof(user_id_update_autofills__RAND__) == 'function') user_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/billing_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/billing_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return billing_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return billing_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return billing_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#user_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#user_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#name').replaceWith('<div class=\"form-control-static\" id=\"name\">' + (jQuery('#name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#phone_number').replaceWith('<div class=\"form-control-static\" id=\"phone_number\">' + (jQuery('#phone_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#tx_ref').replaceWith('<div class=\"form-control-static\" id=\"tx_ref\">' + (jQuery('#tx_ref').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#charged_amount').replaceWith('<div class=\"form-control-static\" id=\"charged_amount\">' + (jQuery('#charged_amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#payment_type').replaceWith('<div class=\"form-control-static\" id=\"payment_type\">' + (jQuery('#payment_type').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#created_at').replaceWith('<div class=\"form-control-static\" id=\"created_at\">' + (jQuery('#created_at').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#auth_model').replaceWith('<div class=\"form-control-static\" id=\"auth_model\">' + (jQuery('#auth_model').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#device_fingerprint').replaceWith('<div class=\"form-control-static\" id=\"device_fingerprint\">' + (jQuery('#device_fingerprint').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#flw_ref').replaceWith('<div class=\"form-control-static\" id=\"flw_ref\">' + (jQuery('#flw_ref').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#account_id').replaceWith('<div class=\"form-control-static\" id=\"account_id\">' + (jQuery('#account_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#amount_settled').replaceWith('<div class=\"form-control-static\" id=\"amount_settled\">' + (jQuery('#amount_settled').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#app_fee').replaceWith('<div class=\"form-control-static\" id=\"app_fee\">' + (jQuery('#app_fee').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#status').replaceWith('<div class=\"form-control-static\" id=\"status\">' + (jQuery('#status').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(user_id)%%>', $combo_user_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(user_id)%%>', $combo_user_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(user_id)%%>', urlencode($combo_user_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['user_id' => ['users', 'User_id'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(user_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(phone_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tx_ref)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(charged_amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(payment_type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(auth_model)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(device_fingerprint)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(flw_ref)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(account_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(amount_settled)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(app_fee)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(user_id)%%>', safe_html($urow['user_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(user_id)%%>', html_attr($row['user_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(user_id)%%>', urlencode($urow['user_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', safe_html($urow['name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', html_attr($row['name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode($urow['name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(phone_number)%%>', safe_html($urow['phone_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(phone_number)%%>', html_attr($row['phone_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_number)%%>', urlencode($urow['phone_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tx_ref)%%>', safe_html($urow['tx_ref']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tx_ref)%%>', html_attr($row['tx_ref']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tx_ref)%%>', urlencode($urow['tx_ref']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(charged_amount)%%>', safe_html($urow['charged_amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(charged_amount)%%>', html_attr($row['charged_amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(charged_amount)%%>', urlencode($urow['charged_amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(payment_type)%%>', safe_html($urow['payment_type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(payment_type)%%>', html_attr($row['payment_type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(payment_type)%%>', urlencode($urow['payment_type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(created_at)%%>', html_attr($row['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(auth_model)%%>', safe_html($urow['auth_model']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(auth_model)%%>', html_attr($row['auth_model']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(auth_model)%%>', urlencode($urow['auth_model']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(device_fingerprint)%%>', safe_html($urow['device_fingerprint']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(device_fingerprint)%%>', html_attr($row['device_fingerprint']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(device_fingerprint)%%>', urlencode($urow['device_fingerprint']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(flw_ref)%%>', safe_html($urow['flw_ref']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(flw_ref)%%>', html_attr($row['flw_ref']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(flw_ref)%%>', urlencode($urow['flw_ref']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(account_id)%%>', safe_html($urow['account_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(account_id)%%>', html_attr($row['account_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(account_id)%%>', urlencode($urow['account_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(amount_settled)%%>', safe_html($urow['amount_settled']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(amount_settled)%%>', html_attr($row['amount_settled']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount_settled)%%>', urlencode($urow['amount_settled']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(app_fee)%%>', safe_html($urow['app_fee']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(app_fee)%%>', html_attr($row['app_fee']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(app_fee)%%>', urlencode($urow['app_fee']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(user_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(user_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(phone_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tx_ref)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tx_ref)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(charged_amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(charged_amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(payment_type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(payment_type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(auth_model)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(auth_model)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(device_fingerprint)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(device_fingerprint)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(flw_ref)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(flw_ref)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(account_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(account_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(amount_settled)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount_settled)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(app_fee)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(app_fee)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('billing');
	if($selected_id) {
		$jdata = get_joined_record('billing', $selected_id);
		if($jdata === false) $jdata = get_defaults('billing');
		$rdata = $row;
	}
	$templateCode .= loadView('billing-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: billing_dv
	if(function_exists('billing_dv')) {
		$args = [];
		billing_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}