<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/billing.php');
	include_once(__DIR__ . '/billing_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('billing');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'billing';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`billing`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* User_id */" => "user_id",
		"`billing`.`name`" => "name",
		"`billing`.`email`" => "email",
		"`billing`.`phone_number`" => "phone_number",
		"`billing`.`tx_ref`" => "tx_ref",
		"`billing`.`charged_amount`" => "charged_amount",
		"`billing`.`payment_type`" => "payment_type",
		"`billing`.`created_at`" => "created_at",
		"`billing`.`auth_model`" => "auth_model",
		"`billing`.`device_fingerprint`" => "device_fingerprint",
		"`billing`.`flw_ref`" => "flw_ref",
		"`billing`.`account_id`" => "account_id",
		"`billing`.`amount_settled`" => "amount_settled",
		"`billing`.`app_fee`" => "app_fee",
		"`billing`.`status`" => "status",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`billing`.`id`',
		2 => '`users1`.`id`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`billing`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* User_id */" => "user_id",
		"`billing`.`name`" => "name",
		"`billing`.`email`" => "email",
		"`billing`.`phone_number`" => "phone_number",
		"`billing`.`tx_ref`" => "tx_ref",
		"`billing`.`charged_amount`" => "charged_amount",
		"`billing`.`payment_type`" => "payment_type",
		"`billing`.`created_at`" => "created_at",
		"`billing`.`auth_model`" => "auth_model",
		"`billing`.`device_fingerprint`" => "device_fingerprint",
		"`billing`.`flw_ref`" => "flw_ref",
		"`billing`.`account_id`" => "account_id",
		"`billing`.`amount_settled`" => "amount_settled",
		"`billing`.`app_fee`" => "app_fee",
		"`billing`.`status`" => "status",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`billing`.`id`" => "Id",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* User_id */" => "User_id",
		"`billing`.`name`" => "Name",
		"`billing`.`email`" => "Email",
		"`billing`.`phone_number`" => "Phone_number",
		"`billing`.`tx_ref`" => "Tx_ref",
		"`billing`.`charged_amount`" => "Charged_amount",
		"`billing`.`payment_type`" => "Payment_type",
		"`billing`.`created_at`" => "Created_at",
		"`billing`.`auth_model`" => "Auth_model",
		"`billing`.`device_fingerprint`" => "Device_fingerprint",
		"`billing`.`flw_ref`" => "Flw_ref",
		"`billing`.`account_id`" => "Account_id",
		"`billing`.`amount_settled`" => "Amount_settled",
		"`billing`.`app_fee`" => "App_fee",
		"`billing`.`status`" => "Status",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`billing`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* User_id */" => "user_id",
		"`billing`.`name`" => "name",
		"`billing`.`email`" => "email",
		"`billing`.`phone_number`" => "phone_number",
		"`billing`.`tx_ref`" => "tx_ref",
		"`billing`.`charged_amount`" => "charged_amount",
		"`billing`.`payment_type`" => "payment_type",
		"`billing`.`created_at`" => "created_at",
		"`billing`.`auth_model`" => "auth_model",
		"`billing`.`device_fingerprint`" => "device_fingerprint",
		"`billing`.`flw_ref`" => "flw_ref",
		"`billing`.`account_id`" => "account_id",
		"`billing`.`amount_settled`" => "amount_settled",
		"`billing`.`app_fee`" => "app_fee",
		"`billing`.`status`" => "status",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['user_id' => 'User_id', ];

	$x->QueryFrom = "`billing` LEFT JOIN `users` as users1 ON `users1`.`id`=`billing`.`user_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'billing_view.php';
	$x->TableTitle = 'Billing';
	$x->TableIcon = 'resources/table_icons/money_dollar.png';
	$x->PrimaryKey = '`billing`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'User_id', 'Name', 'Email', 'Phone_number', 'Tx_ref', 'Charged_amount', 'Payment_type', 'Created_at', 'Auth_model', 'Device_fingerprint', 'Flw_ref', 'Account_id', 'Amount_settled', 'App_fee', 'Status', ];
	$x->ColFieldName = ['id', 'user_id', 'name', 'email', 'phone_number', 'tx_ref', 'charged_amount', 'payment_type', 'created_at', 'auth_model', 'device_fingerprint', 'flw_ref', 'account_id', 'amount_settled', 'app_fee', 'status', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/billing_templateTV.html';
	$x->SelectedTemplate = 'templates/billing_templateTVS.html';
	$x->TemplateDV = 'templates/billing_templateDV.html';
	$x->TemplateDVP = 'templates/billing_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: billing_init
	$render = true;
	if(function_exists('billing_init')) {
		$args = [];
		$render = billing_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: billing_header
	$headerCode = '';
	if(function_exists('billing_header')) {
		$args = [];
		$headerCode = billing_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: billing_footer
	$footerCode = '';
	if(function_exists('billing_footer')) {
		$args = [];
		$footerCode = billing_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
