<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/bot_control.php');
	include_once(__DIR__ . '/bot_control_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('bot_control');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'bot_control';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`bot_control`.`id`" => "id",
		"`bot_control`.`source`" => "source",
		"`bot_control`.`deep_link`" => "deep_link",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`bot_control`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`bot_control`.`id`" => "id",
		"`bot_control`.`source`" => "source",
		"`bot_control`.`deep_link`" => "deep_link",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`bot_control`.`id`" => "Id",
		"`bot_control`.`source`" => "Source",
		"`bot_control`.`deep_link`" => "Deep_link",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`bot_control`.`id`" => "id",
		"`bot_control`.`source`" => "source",
		"`bot_control`.`deep_link`" => "deep_link",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`bot_control` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'bot_control_view.php';
	$x->TableTitle = 'Bot_control';
	$x->TableIcon = 'resources/table_icons/agp.png';
	$x->PrimaryKey = '`bot_control`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Id', 'Source', 'Deep_link', ];
	$x->ColFieldName = ['id', 'source', 'deep_link', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/bot_control_templateTV.html';
	$x->SelectedTemplate = 'templates/bot_control_templateTVS.html';
	$x->TemplateDV = 'templates/bot_control_templateDV.html';
	$x->TemplateDVP = 'templates/bot_control_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: bot_control_init
	$render = true;
	if(function_exists('bot_control_init')) {
		$args = [];
		$render = bot_control_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: bot_control_header
	$headerCode = '';
	if(function_exists('bot_control_header')) {
		$args = [];
		$headerCode = bot_control_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: bot_control_footer
	$footerCode = '';
	if(function_exists('bot_control_footer')) {
		$args = [];
		$footerCode = bot_control_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
