<?php

// Data functions (insert, update, delete, form) for table history

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function history_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('history');
	if(!$arrPerm['insert']) return false;

	$data = [
		'id' => Request::val('id', ''),
		'email' => Request::val('email', ''),
		'password' => Request::val('password', ''),
		'type' => Request::val('type', ''),
		'firstname' => Request::val('firstname', ''),
		'lastname' => Request::val('lastname', ''),
		'username' => Request::val('username', ''),
		'address' => Request::val('address', ''),
		'country' => Request::val('country', 'Kenya'),
		'contact_info' => Request::val('contact_info', ''),
		'contact_verify' => Request::val('contact_verify', '0'),
		'photo' => Request::val('photo', ''),
		'status' => Request::val('status', ''),
		'activate_code' => Request::val('activate_code', ''),
		'reset_code' => Request::val('reset_code', ''),
		'created_on' => Request::val('created_on', ''),
		'source' => Request::val('source', ''),
		'verified' => Request::val('verified', ''),
		'occupation' => Request::val('occupation', 'Investor'),
		'company' => Request::val('company', ''),
		'company_site' => Request::val('company_site', ''),
		'language' => Request::val('language', ''),
		'time_zone' => Request::val('time_zone', ''),
		'currency' => Request::val('currency', ''),
		'email_comm' => Request::val('email_comm', ''),
		'phone_comm' => Request::val('phone_comm', ''),
		'marketing' => Request::val('marketing', ''),
		'two_auth' => Request::val('two_auth', '0'),
		'two_auth_secret' => Request::val('two_auth_secret', ''),
		'g_id' => Request::val('g_id', ''),
		'f_id' => Request::val('f_id', ''),
		't_id' => Request::val('t_id', ''),
		'timestamp' => Request::val('timestamp', 'current_timestamp()'),
		'change_part' => Request::val('change_part', ''),
	];


	// hook: history_before_insert
	if(function_exists('history_before_insert')) {
		$args = [];
		if(!history_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('history', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('history', $recID, calculated_fields()['history']);

	// hook: history_after_insert
	if(function_exists('history_after_insert')) {
		$res = sql("SELECT * FROM `history` WHERE `hist_id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!history_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('history', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) history_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function history_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function history_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('history', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: history_before_delete
	if(function_exists('history_before_delete')) {
		$args = [];
		if(!history_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `history` WHERE `hist_id`='{$selected_id}'", $eo);

	// hook: history_after_delete
	if(function_exists('history_after_delete')) {
		$args = [];
		history_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='history' AND `pkValue`='{$selected_id}'", $eo);
}

function history_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('history', $selected_id, 'edit')) return false;

	$data = [
		'id' => Request::val('id', ''),
		'email' => Request::val('email', ''),
		'password' => Request::val('password', ''),
		'type' => Request::val('type', ''),
		'firstname' => Request::val('firstname', ''),
		'lastname' => Request::val('lastname', ''),
		'username' => Request::val('username', ''),
		'address' => Request::val('address', ''),
		'country' => Request::val('country', ''),
		'contact_info' => Request::val('contact_info', ''),
		'contact_verify' => Request::val('contact_verify', ''),
		'photo' => Request::val('photo', ''),
		'status' => Request::val('status', ''),
		'activate_code' => Request::val('activate_code', ''),
		'reset_code' => Request::val('reset_code', ''),
		'created_on' => Request::val('created_on', ''),
		'source' => Request::val('source', ''),
		'verified' => Request::val('verified', ''),
		'occupation' => Request::val('occupation', ''),
		'company' => Request::val('company', ''),
		'company_site' => Request::val('company_site', ''),
		'language' => Request::val('language', ''),
		'time_zone' => Request::val('time_zone', ''),
		'currency' => Request::val('currency', ''),
		'email_comm' => Request::val('email_comm', ''),
		'phone_comm' => Request::val('phone_comm', ''),
		'marketing' => Request::val('marketing', ''),
		'two_auth' => Request::val('two_auth', ''),
		'two_auth_secret' => Request::val('two_auth_secret', ''),
		'g_id' => Request::val('g_id', ''),
		'f_id' => Request::val('f_id', ''),
		't_id' => Request::val('t_id', ''),
		'timestamp' => Request::val('timestamp', ''),
		'change_part' => Request::val('change_part', ''),
	];

	// get existing values
	$old_data = getRecord('history', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: history_before_update
	if(function_exists('history_before_update')) {
		$args = ['old_data' => $old_data];
		if(!history_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'history', 
		backtick_keys_once($set), 
		['`hist_id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="history_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('history', $data['selectedID'], calculated_fields()['history']);

	// hook: history_after_update
	if(function_exists('history_after_update')) {
		$res = sql("SELECT * FROM `history` WHERE `hist_id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['hist_id'];
		$args = ['old_data' => $old_data];
		if(!history_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='history' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function history_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('history');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='history' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='history' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `history` WHERE `hist_id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'history_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/history_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/history_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return history_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return history_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return history_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#id').replaceWith('<div class=\"form-control-static\" id=\"id\">' + (jQuery('#id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#password').replaceWith('<div class=\"form-control-static\" id=\"password\">' + (jQuery('#password').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#type').replaceWith('<div class=\"form-control-static\" id=\"type\">' + (jQuery('#type').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#firstname').replaceWith('<div class=\"form-control-static\" id=\"firstname\">' + (jQuery('#firstname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#lastname').replaceWith('<div class=\"form-control-static\" id=\"lastname\">' + (jQuery('#lastname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#username').replaceWith('<div class=\"form-control-static\" id=\"username\">' + (jQuery('#username').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#address').replaceWith('<div class=\"form-control-static\" id=\"address\">' + (jQuery('#address').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#country').replaceWith('<div class=\"form-control-static\" id=\"country\">' + (jQuery('#country').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#contact_info').replaceWith('<div class=\"form-control-static\" id=\"contact_info\">' + (jQuery('#contact_info').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#contact_verify').replaceWith('<div class=\"form-control-static\" id=\"contact_verify\">' + (jQuery('#contact_verify').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#photo').replaceWith('<div class=\"form-control-static\" id=\"photo\">' + (jQuery('#photo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#status').replaceWith('<div class=\"form-control-static\" id=\"status\">' + (jQuery('#status').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#activate_code').replaceWith('<div class=\"form-control-static\" id=\"activate_code\">' + (jQuery('#activate_code').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#reset_code').replaceWith('<div class=\"form-control-static\" id=\"reset_code\">' + (jQuery('#reset_code').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#created_on').replaceWith('<div class=\"form-control-static\" id=\"created_on\">' + (jQuery('#created_on').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#source').replaceWith('<div class=\"form-control-static\" id=\"source\">' + (jQuery('#source').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#verified').replaceWith('<div class=\"form-control-static\" id=\"verified\">' + (jQuery('#verified').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#occupation').replaceWith('<div class=\"form-control-static\" id=\"occupation\">' + (jQuery('#occupation').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#company').replaceWith('<div class=\"form-control-static\" id=\"company\">' + (jQuery('#company').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#company_site').replaceWith('<div class=\"form-control-static\" id=\"company_site\">' + (jQuery('#company_site').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#language').replaceWith('<div class=\"form-control-static\" id=\"language\">' + (jQuery('#language').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#time_zone').replaceWith('<div class=\"form-control-static\" id=\"time_zone\">' + (jQuery('#time_zone').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#currency').replaceWith('<div class=\"form-control-static\" id=\"currency\">' + (jQuery('#currency').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email_comm').replaceWith('<div class=\"form-control-static\" id=\"email_comm\">' + (jQuery('#email_comm').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#phone_comm').replaceWith('<div class=\"form-control-static\" id=\"phone_comm\">' + (jQuery('#phone_comm').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#marketing').replaceWith('<div class=\"form-control-static\" id=\"marketing\">' + (jQuery('#marketing').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#two_auth').replaceWith('<div class=\"form-control-static\" id=\"two_auth\">' + (jQuery('#two_auth').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#two_auth_secret').replaceWith('<div class=\"form-control-static\" id=\"two_auth_secret\">' + (jQuery('#two_auth_secret').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#g_id').replaceWith('<div class=\"form-control-static\" id=\"g_id\">' + (jQuery('#g_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#f_id').replaceWith('<div class=\"form-control-static\" id=\"f_id\">' + (jQuery('#f_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#t_id').replaceWith('<div class=\"form-control-static\" id=\"t_id\">' + (jQuery('#t_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#timestamp').replaceWith('<div class=\"form-control-static\" id=\"timestamp\">' + (jQuery('#timestamp').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#change_part').replaceWith('<div class=\"form-control-static\" id=\"change_part\">' + (jQuery('#change_part').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(hist_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(password)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(firstname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(lastname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(address)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(country)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contact_info)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contact_verify)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(photo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(activate_code)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(reset_code)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_on)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(source)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(verified)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(occupation)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(company)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(company_site)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(language)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(time_zone)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(currency)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email_comm)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(phone_comm)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(marketing)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(two_auth)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(two_auth_secret)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(g_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(f_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(t_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(timestamp)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(change_part)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hist_id)%%>', safe_html($urow['hist_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hist_id)%%>', html_attr($row['hist_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hist_id)%%>', urlencode($urow['hist_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(password)%%>', safe_html($urow['password']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(password)%%>', html_attr($row['password']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(password)%%>', urlencode($urow['password']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', safe_html($urow['type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(type)%%>', html_attr($row['type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode($urow['type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(firstname)%%>', safe_html($urow['firstname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(firstname)%%>', html_attr($row['firstname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(firstname)%%>', urlencode($urow['firstname']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(lastname)%%>', safe_html($urow['lastname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(lastname)%%>', html_attr($row['lastname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lastname)%%>', urlencode($urow['lastname']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(username)%%>', safe_html($urow['username']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(username)%%>', html_attr($row['username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(username)%%>', urlencode($urow['username']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(address)%%>', safe_html($urow['address']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(address)%%>', html_attr($row['address']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(address)%%>', urlencode($urow['address']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(country)%%>', safe_html($urow['country']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(country)%%>', html_attr($row['country']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(country)%%>', urlencode($urow['country']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contact_info)%%>', safe_html($urow['contact_info']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contact_info)%%>', html_attr($row['contact_info']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_info)%%>', urlencode($urow['contact_info']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contact_verify)%%>', safe_html($urow['contact_verify']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contact_verify)%%>', html_attr($row['contact_verify']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_verify)%%>', urlencode($urow['contact_verify']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(photo)%%>', safe_html($urow['photo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(photo)%%>', html_attr($row['photo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(photo)%%>', urlencode($urow['photo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(activate_code)%%>', safe_html($urow['activate_code']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(activate_code)%%>', html_attr($row['activate_code']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(activate_code)%%>', urlencode($urow['activate_code']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(reset_code)%%>', safe_html($urow['reset_code']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(reset_code)%%>', html_attr($row['reset_code']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reset_code)%%>', urlencode($urow['reset_code']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(created_on)%%>', safe_html($urow['created_on']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(created_on)%%>', html_attr($row['created_on']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_on)%%>', urlencode($urow['created_on']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(source)%%>', safe_html($urow['source']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(source)%%>', html_attr($row['source']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(source)%%>', urlencode($urow['source']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(verified)%%>', safe_html($urow['verified']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(verified)%%>', html_attr($row['verified']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(verified)%%>', urlencode($urow['verified']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(occupation)%%>', safe_html($urow['occupation']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(occupation)%%>', html_attr($row['occupation']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(occupation)%%>', urlencode($urow['occupation']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(company)%%>', safe_html($urow['company']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(company)%%>', html_attr($row['company']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company)%%>', urlencode($urow['company']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(company_site)%%>', safe_html($urow['company_site']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(company_site)%%>', html_attr($row['company_site']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company_site)%%>', urlencode($urow['company_site']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(language)%%>', safe_html($urow['language']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(language)%%>', html_attr($row['language']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(language)%%>', urlencode($urow['language']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(time_zone)%%>', safe_html($urow['time_zone']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(time_zone)%%>', html_attr($row['time_zone']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_zone)%%>', urlencode($urow['time_zone']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(currency)%%>', safe_html($urow['currency']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(currency)%%>', html_attr($row['currency']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(currency)%%>', urlencode($urow['currency']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email_comm)%%>', safe_html($urow['email_comm']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email_comm)%%>', html_attr($row['email_comm']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_comm)%%>', urlencode($urow['email_comm']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(phone_comm)%%>', safe_html($urow['phone_comm']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(phone_comm)%%>', html_attr($row['phone_comm']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_comm)%%>', urlencode($urow['phone_comm']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(marketing)%%>', safe_html($urow['marketing']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(marketing)%%>', html_attr($row['marketing']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(marketing)%%>', urlencode($urow['marketing']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(two_auth)%%>', safe_html($urow['two_auth']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(two_auth)%%>', html_attr($row['two_auth']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(two_auth)%%>', urlencode($urow['two_auth']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(two_auth_secret)%%>', safe_html($urow['two_auth_secret']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(two_auth_secret)%%>', html_attr($row['two_auth_secret']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(two_auth_secret)%%>', urlencode($urow['two_auth_secret']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(g_id)%%>', safe_html($urow['g_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(g_id)%%>', html_attr($row['g_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(g_id)%%>', urlencode($urow['g_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(f_id)%%>', safe_html($urow['f_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(f_id)%%>', html_attr($row['f_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(f_id)%%>', urlencode($urow['f_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(t_id)%%>', safe_html($urow['t_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(t_id)%%>', html_attr($row['t_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(t_id)%%>', urlencode($urow['t_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(timestamp)%%>', safe_html($urow['timestamp']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(timestamp)%%>', html_attr($row['timestamp']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(timestamp)%%>', urlencode($urow['timestamp']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(change_part)%%>', safe_html($urow['change_part']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(change_part)%%>', html_attr($row['change_part']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(change_part)%%>', urlencode($urow['change_part']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(hist_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hist_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(password)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(password)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(firstname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(firstname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(lastname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lastname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(address)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(address)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(country)%%>', 'Kenya', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(country)%%>', urlencode('Kenya'), $templateCode);
		$templateCode = str_replace('<%%VALUE(contact_info)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_info)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(contact_verify)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact_verify)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(photo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(photo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(activate_code)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(activate_code)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(reset_code)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(reset_code)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_on)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_on)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(source)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(source)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(verified)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(verified)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(occupation)%%>', 'Investor', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(occupation)%%>', urlencode('Investor'), $templateCode);
		$templateCode = str_replace('<%%VALUE(company)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(company_site)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(company_site)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(language)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(language)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_zone)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_zone)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(currency)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(currency)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email_comm)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_comm)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(phone_comm)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_comm)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(marketing)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(marketing)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(two_auth)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(two_auth)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(two_auth_secret)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(two_auth_secret)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(g_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(g_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(f_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(f_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(t_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(t_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(timestamp)%%>', 'current_timestamp()', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(timestamp)%%>', urlencode('current_timestamp()'), $templateCode);
		$templateCode = str_replace('<%%VALUE(change_part)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(change_part)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('history');
	if($selected_id) {
		$jdata = get_joined_record('history', $selected_id);
		if($jdata === false) $jdata = get_defaults('history');
		$rdata = $row;
	}
	$templateCode .= loadView('history-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: history_dv
	if(function_exists('history_dv')) {
		$args = [];
		history_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}