<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/history.php');
	include_once(__DIR__ . '/history_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('history');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'history';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`history`.`hist_id`" => "hist_id",
		"`history`.`id`" => "id",
		"`history`.`email`" => "email",
		"`history`.`password`" => "password",
		"`history`.`type`" => "type",
		"`history`.`firstname`" => "firstname",
		"`history`.`lastname`" => "lastname",
		"`history`.`username`" => "username",
		"`history`.`address`" => "address",
		"`history`.`country`" => "country",
		"`history`.`contact_info`" => "contact_info",
		"`history`.`contact_verify`" => "contact_verify",
		"`history`.`photo`" => "photo",
		"`history`.`status`" => "status",
		"`history`.`activate_code`" => "activate_code",
		"`history`.`reset_code`" => "reset_code",
		"`history`.`created_on`" => "created_on",
		"`history`.`source`" => "source",
		"`history`.`verified`" => "verified",
		"`history`.`occupation`" => "occupation",
		"`history`.`company`" => "company",
		"`history`.`company_site`" => "company_site",
		"`history`.`language`" => "language",
		"`history`.`time_zone`" => "time_zone",
		"`history`.`currency`" => "currency",
		"`history`.`email_comm`" => "email_comm",
		"`history`.`phone_comm`" => "phone_comm",
		"`history`.`marketing`" => "marketing",
		"`history`.`two_auth`" => "two_auth",
		"`history`.`two_auth_secret`" => "two_auth_secret",
		"`history`.`g_id`" => "g_id",
		"`history`.`f_id`" => "f_id",
		"`history`.`t_id`" => "t_id",
		"`history`.`timestamp`" => "timestamp",
		"`history`.`change_part`" => "change_part",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`history`.`hist_id`',
		2 => '`history`.`id`',
		3 => 3,
		4 => 4,
		5 => '`history`.`type`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => '`history`.`contact_verify`',
		13 => 13,
		14 => '`history`.`status`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => '`history`.`email_comm`',
		27 => '`history`.`phone_comm`',
		28 => '`history`.`marketing`',
		29 => '`history`.`two_auth`',
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => '`history`.`timestamp`',
		35 => 35,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`history`.`hist_id`" => "hist_id",
		"`history`.`id`" => "id",
		"`history`.`email`" => "email",
		"`history`.`password`" => "password",
		"`history`.`type`" => "type",
		"`history`.`firstname`" => "firstname",
		"`history`.`lastname`" => "lastname",
		"`history`.`username`" => "username",
		"`history`.`address`" => "address",
		"`history`.`country`" => "country",
		"`history`.`contact_info`" => "contact_info",
		"`history`.`contact_verify`" => "contact_verify",
		"`history`.`photo`" => "photo",
		"`history`.`status`" => "status",
		"`history`.`activate_code`" => "activate_code",
		"`history`.`reset_code`" => "reset_code",
		"`history`.`created_on`" => "created_on",
		"`history`.`source`" => "source",
		"`history`.`verified`" => "verified",
		"`history`.`occupation`" => "occupation",
		"`history`.`company`" => "company",
		"`history`.`company_site`" => "company_site",
		"`history`.`language`" => "language",
		"`history`.`time_zone`" => "time_zone",
		"`history`.`currency`" => "currency",
		"`history`.`email_comm`" => "email_comm",
		"`history`.`phone_comm`" => "phone_comm",
		"`history`.`marketing`" => "marketing",
		"`history`.`two_auth`" => "two_auth",
		"`history`.`two_auth_secret`" => "two_auth_secret",
		"`history`.`g_id`" => "g_id",
		"`history`.`f_id`" => "f_id",
		"`history`.`t_id`" => "t_id",
		"`history`.`timestamp`" => "timestamp",
		"`history`.`change_part`" => "change_part",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`history`.`hist_id`" => "Hist_id",
		"`history`.`id`" => "Id",
		"`history`.`email`" => "Email",
		"`history`.`password`" => "Password",
		"`history`.`type`" => "Type",
		"`history`.`firstname`" => "Firstname",
		"`history`.`lastname`" => "Lastname",
		"`history`.`username`" => "Username",
		"`history`.`address`" => "Address",
		"`history`.`country`" => "Country",
		"`history`.`contact_info`" => "Contact_info",
		"`history`.`contact_verify`" => "Contact_verify",
		"`history`.`photo`" => "Photo",
		"`history`.`status`" => "Status",
		"`history`.`activate_code`" => "Activate_code",
		"`history`.`reset_code`" => "Reset_code",
		"`history`.`created_on`" => "Created_on",
		"`history`.`source`" => "Source",
		"`history`.`verified`" => "Verified",
		"`history`.`occupation`" => "Occupation",
		"`history`.`company`" => "Company",
		"`history`.`company_site`" => "Company_site",
		"`history`.`language`" => "Language",
		"`history`.`time_zone`" => "Time_zone",
		"`history`.`currency`" => "Currency",
		"`history`.`email_comm`" => "Email_comm",
		"`history`.`phone_comm`" => "Phone_comm",
		"`history`.`marketing`" => "Marketing",
		"`history`.`two_auth`" => "Two_auth",
		"`history`.`two_auth_secret`" => "Two_auth_secret",
		"`history`.`g_id`" => "G_id",
		"`history`.`f_id`" => "F_id",
		"`history`.`t_id`" => "T_id",
		"`history`.`timestamp`" => "Timestamp",
		"`history`.`change_part`" => "Change_part",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`history`.`hist_id`" => "hist_id",
		"`history`.`id`" => "id",
		"`history`.`email`" => "email",
		"`history`.`password`" => "password",
		"`history`.`type`" => "type",
		"`history`.`firstname`" => "firstname",
		"`history`.`lastname`" => "lastname",
		"`history`.`username`" => "username",
		"`history`.`address`" => "address",
		"`history`.`country`" => "country",
		"`history`.`contact_info`" => "contact_info",
		"`history`.`contact_verify`" => "contact_verify",
		"`history`.`photo`" => "photo",
		"`history`.`status`" => "status",
		"`history`.`activate_code`" => "activate_code",
		"`history`.`reset_code`" => "reset_code",
		"`history`.`created_on`" => "created_on",
		"`history`.`source`" => "source",
		"`history`.`verified`" => "verified",
		"`history`.`occupation`" => "occupation",
		"`history`.`company`" => "company",
		"`history`.`company_site`" => "company_site",
		"`history`.`language`" => "language",
		"`history`.`time_zone`" => "time_zone",
		"`history`.`currency`" => "currency",
		"`history`.`email_comm`" => "email_comm",
		"`history`.`phone_comm`" => "phone_comm",
		"`history`.`marketing`" => "marketing",
		"`history`.`two_auth`" => "two_auth",
		"`history`.`two_auth_secret`" => "two_auth_secret",
		"`history`.`g_id`" => "g_id",
		"`history`.`f_id`" => "f_id",
		"`history`.`t_id`" => "t_id",
		"`history`.`timestamp`" => "timestamp",
		"`history`.`change_part`" => "change_part",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`history` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'history_view.php';
	$x->TableTitle = 'History';
	$x->TableIcon = 'resources/table_icons/clock_history_frame.png';
	$x->PrimaryKey = '`history`.`hist_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Hist_id', 'Id', 'Email', 'Password', 'Type', 'Firstname', 'Lastname', 'Username', 'Address', 'Country', 'Contact_info', 'Contact_verify', 'Photo', 'Status', 'Activate_code', 'Reset_code', 'Created_on', 'Source', 'Verified', 'Occupation', 'Company', 'Company_site', 'Language', 'Time_zone', 'Currency', 'Email_comm', 'Phone_comm', 'Marketing', 'Two_auth', 'Two_auth_secret', 'G_id', 'F_id', 'T_id', 'Timestamp', 'Change_part', ];
	$x->ColFieldName = ['hist_id', 'id', 'email', 'password', 'type', 'firstname', 'lastname', 'username', 'address', 'country', 'contact_info', 'contact_verify', 'photo', 'status', 'activate_code', 'reset_code', 'created_on', 'source', 'verified', 'occupation', 'company', 'company_site', 'language', 'time_zone', 'currency', 'email_comm', 'phone_comm', 'marketing', 'two_auth', 'two_auth_secret', 'g_id', 'f_id', 't_id', 'timestamp', 'change_part', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/history_templateTV.html';
	$x->SelectedTemplate = 'templates/history_templateTVS.html';
	$x->TemplateDV = 'templates/history_templateDV.html';
	$x->TemplateDVP = 'templates/history_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: history_init
	$render = true;
	if(function_exists('history_init')) {
		$args = [];
		$render = history_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: history_header
	$headerCode = '';
	if(function_exists('history_header')) {
		$args = [];
		$headerCode = history_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: history_footer
	$footerCode = '';
	if(function_exists('history_footer')) {
		$args = [];
		$footerCode = history_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
