<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/process_engine.php');
	include_once(__DIR__ . '/process_engine_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('process_engine');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'process_engine';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`process_engine`.`id`" => "id",
		"`process_engine`.`request_method`" => "request_method",
		"`process_engine`.`page`" => "page",
		"`process_engine`.`var_1`" => "var_1",
		"`process_engine`.`object`" => "object",
		"`process_engine`.`access_token`" => "access_token",
		"`process_engine`.`access_secret`" => "access_secret",
		"`process_engine`.`execution`" => "execution",
		"`process_engine`.`user_id`" => "user_id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`process_engine`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`process_engine`.`id`" => "id",
		"`process_engine`.`request_method`" => "request_method",
		"`process_engine`.`page`" => "page",
		"`process_engine`.`var_1`" => "var_1",
		"`process_engine`.`object`" => "object",
		"`process_engine`.`access_token`" => "access_token",
		"`process_engine`.`access_secret`" => "access_secret",
		"`process_engine`.`execution`" => "execution",
		"`process_engine`.`user_id`" => "user_id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`process_engine`.`id`" => "Id",
		"`process_engine`.`request_method`" => "Request_method",
		"`process_engine`.`page`" => "Page",
		"`process_engine`.`var_1`" => "Var_1",
		"`process_engine`.`object`" => "Object",
		"`process_engine`.`access_token`" => "Access_token",
		"`process_engine`.`access_secret`" => "Access_secret",
		"`process_engine`.`execution`" => "Execution",
		"`process_engine`.`user_id`" => "User_id",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`process_engine`.`id`" => "id",
		"`process_engine`.`request_method`" => "request_method",
		"`process_engine`.`page`" => "page",
		"`process_engine`.`var_1`" => "var_1",
		"`process_engine`.`object`" => "object",
		"`process_engine`.`access_token`" => "access_token",
		"`process_engine`.`access_secret`" => "access_secret",
		"`process_engine`.`execution`" => "execution",
		"`process_engine`.`user_id`" => "user_id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`process_engine` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'process_engine_view.php';
	$x->TableTitle = 'Process_engine';
	$x->TableIcon = 'resources/table_icons/processor.png';
	$x->PrimaryKey = '`process_engine`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Request_method', 'Page', 'Var_1', 'Object', 'Access_token', 'Access_secret', 'Execution', 'User_id', ];
	$x->ColFieldName = ['id', 'request_method', 'page', 'var_1', 'object', 'access_token', 'access_secret', 'execution', 'user_id', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/process_engine_templateTV.html';
	$x->SelectedTemplate = 'templates/process_engine_templateTVS.html';
	$x->TemplateDV = 'templates/process_engine_templateDV.html';
	$x->TemplateDVP = 'templates/process_engine_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: process_engine_init
	$render = true;
	if(function_exists('process_engine_init')) {
		$args = [];
		$render = process_engine_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: process_engine_header
	$headerCode = '';
	if(function_exists('process_engine_header')) {
		$args = [];
		$headerCode = process_engine_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: process_engine_footer
	$footerCode = '';
	if(function_exists('process_engine_footer')) {
		$args = [];
		$footerCode = process_engine_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
