<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/system_tokens.php');
	include_once(__DIR__ . '/system_tokens_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('system_tokens');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'system_tokens';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`system_tokens`.`id`" => "id",
		"`system_tokens`.`bearer_token`" => "bearer_token",
		"`system_tokens`.`consumer_key`" => "consumer_key",
		"`system_tokens`.`consumer_secret`" => "consumer_secret",
		"`system_tokens`.`api`" => "api",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`system_tokens`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`system_tokens`.`id`" => "id",
		"`system_tokens`.`bearer_token`" => "bearer_token",
		"`system_tokens`.`consumer_key`" => "consumer_key",
		"`system_tokens`.`consumer_secret`" => "consumer_secret",
		"`system_tokens`.`api`" => "api",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`system_tokens`.`id`" => "Id",
		"`system_tokens`.`bearer_token`" => "Bearer_token",
		"`system_tokens`.`consumer_key`" => "Consumer_key",
		"`system_tokens`.`consumer_secret`" => "Consumer_secret",
		"`system_tokens`.`api`" => "Api",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`system_tokens`.`id`" => "id",
		"`system_tokens`.`bearer_token`" => "bearer_token",
		"`system_tokens`.`consumer_key`" => "consumer_key",
		"`system_tokens`.`consumer_secret`" => "consumer_secret",
		"`system_tokens`.`api`" => "api",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`system_tokens` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'system_tokens_view.php';
	$x->TableTitle = 'System_tokens';
	$x->TableIcon = 'resources/table_icons/system_monitor.png';
	$x->PrimaryKey = '`system_tokens`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Bearer_token', 'Consumer_key', 'Consumer_secret', 'Api', ];
	$x->ColFieldName = ['id', 'bearer_token', 'consumer_key', 'consumer_secret', 'api', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/system_tokens_templateTV.html';
	$x->SelectedTemplate = 'templates/system_tokens_templateTVS.html';
	$x->TemplateDV = 'templates/system_tokens_templateDV.html';
	$x->TemplateDVP = 'templates/system_tokens_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: system_tokens_init
	$render = true;
	if(function_exists('system_tokens_init')) {
		$args = [];
		$render = system_tokens_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: system_tokens_header
	$headerCode = '';
	if(function_exists('system_tokens_header')) {
		$args = [];
		$headerCode = system_tokens_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: system_tokens_footer
	$footerCode = '';
	if(function_exists('system_tokens_footer')) {
		$args = [];
		$footerCode = system_tokens_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
