<?php

// Data functions (insert, update, delete, form) for table system_cookies

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function system_cookies_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('system_cookies');
	if(!$arrPerm['insert']) return false;

	$data = [
		'PATH' => Request::val('PATH', ''),
		'HTTP_ACCEPT' => Request::val('HTTP_ACCEPT', ''),
		'HTTP_ACCEPT_ENCODING' => Request::val('HTTP_ACCEPT_ENCODING', ''),
		'HTTP_ACCEPT_LANGUAGE' => Request::val('HTTP_ACCEPT_LANGUAGE', ''),
		'HTTP_COOKIE' => Request::val('HTTP_COOKIE', ''),
		'HTTP_HOST' => Request::val('HTTP_HOST', ''),
		'HTTP_USER_AGENT' => Request::val('HTTP_USER_AGENT', ''),
		'HTTP_CACHE_CONTROL' => Request::val('HTTP_CACHE_CONTROL', ''),
		'HTTP_SEC_CH_UA' => Request::val('HTTP_SEC_CH_UA', ''),
		'HTTP_SEC_CH_UA_MOBILE' => Request::val('HTTP_SEC_CH_UA_MOBILE', ''),
		'HTTP_SEC_CH_UA_PLATFORM' => Request::val('HTTP_SEC_CH_UA_PLATFORM', ''),
		'HTTP_UPGRADE_INSECURE_REQUESTS' => Request::val('HTTP_UPGRADE_INSECURE_REQUESTS', ''),
		'HTTP_SEC_FETCH_SITE' => Request::val('HTTP_SEC_FETCH_SITE', ''),
		'HTTP_SEC_FETCH_MODE' => Request::val('HTTP_SEC_FETCH_MODE', ''),
		'HTTP_SEC_FETCH_USER' => Request::val('HTTP_SEC_FETCH_USER', ''),
		'HTTP_SEC_FETCH_DEST' => Request::val('HTTP_SEC_FETCH_DEST', ''),
		'HTTP_X_HTTPS' => Request::val('HTTP_X_HTTPS', ''),
		'DOCUMENT_ROOT' => Request::val('DOCUMENT_ROOT', ''),
		'REMOTE_ADDR' => Request::val('REMOTE_ADDR', ''),
		'REMOTE_PORT' => Request::val('REMOTE_PORT', ''),
		'SERVER_ADDR' => Request::val('SERVER_ADDR', ''),
		'SERVER_NAME' => Request::val('SERVER_NAME', ''),
		'SERVER_ADMIN' => Request::val('SERVER_ADMIN', ''),
		'SERVER_PORT' => Request::val('SERVER_PORT', ''),
		'REQUEST_SCHEME' => Request::val('REQUEST_SCHEME', ''),
		'REQUEST_URI' => Request::val('REQUEST_URI', ''),
		'GEOIP_ADDR' => Request::val('GEOIP_ADDR', ''),
		'GEOIP_CONTINENT_CODE' => Request::val('GEOIP_CONTINENT_CODE', ''),
		'GEOIP_COUNTRY_CODE' => Request::val('GEOIP_COUNTRY_CODE', ''),
		'GEOIP_COUNTRY_NAME' => Request::val('GEOIP_COUNTRY_NAME', ''),
		'GEOIP_CITY' => Request::val('GEOIP_CITY', ''),
		'GEOIP_CITY_CONTINENT_CODE' => Request::val('GEOIP_CITY_CONTINENT_CODE', ''),
		'GEOIP_CITY_COUNTRY_CODE' => Request::val('GEOIP_CITY_COUNTRY_CODE', ''),
		'GEOIP_CITY_COUNTRY_NAME' => Request::val('GEOIP_CITY_COUNTRY_NAME', ''),
		'GEOIP_REGION' => Request::val('GEOIP_REGION', ''),
		'GEOIP_LATITUDE' => Request::val('GEOIP_LATITUDE', ''),
		'GEOIP_LONGITUDE' => Request::val('GEOIP_LONGITUDE', ''),
		'GEOIP_ISP' => Request::val('GEOIP_ISP', ''),
		'GEOIP_ORGANIZATION' => Request::val('GEOIP_ORGANIZATION', ''),
		'GEOIP_POSTAL_CODE' => Request::val('GEOIP_POSTAL_CODE', ''),
		'GEOIP_DMA_CODE' => Request::val('GEOIP_DMA_CODE', ''),
		'HTTPS' => Request::val('HTTPS', ''),
		'CRAWLER_USLEEP' => Request::val('CRAWLER_USLEEP', ''),
		'CRAWLER_LOAD_LIMIT_ENFORCE' => Request::val('CRAWLER_LOAD_LIMIT_ENFORCE', ''),
		'X_SPDY' => Request::val('X_SPDY', ''),
		'SSL_PROTOCOL' => Request::val('SSL_PROTOCOL', ''),
		'SSL_CIPHER' => Request::val('SSL_CIPHER', ''),
		'SSL_CIPHER_USEKEYSIZE' => Request::val('SSL_CIPHER_USEKEYSIZE', ''),
		'SSL_CIPHER_ALGKEYSIZE' => Request::val('SSL_CIPHER_ALGKEYSIZE', ''),
		'SCRIPT_FILENAME' => Request::val('SCRIPT_FILENAME', ''),
		'QUERY_STRING' => Request::val('QUERY_STRING', ''),
		'SCRIPT_URI' => Request::val('SCRIPT_URI', ''),
		'SCRIPT_URL' => Request::val('SCRIPT_URL', ''),
		'SCRIPT_NAME' => Request::val('SCRIPT_NAME', ''),
		'SERVER_PROTOCOL' => Request::val('SERVER_PROTOCOL', ''),
		'SERVER_SOFTWARE' => Request::val('SERVER_SOFTWARE', ''),
		'REQUEST_METHOD' => Request::val('REQUEST_METHOD', ''),
		'PHP_SELF' => Request::val('PHP_SELF', ''),
		'REQUEST_TIME_FLOAT' => Request::val('REQUEST_TIME_FLOAT', ''),
		'REQUEST_TIME' => Request::val('REQUEST_TIME', ''),
		'HTTP_REFERER' => Request::val('HTTP_REFERER', ''),
		'REDIRECT_URL' => Request::val('REDIRECT_URL', ''),
		'REDIRECT_REQUEST_METHOD' => Request::val('REDIRECT_REQUEST_METHOD', ''),
		'REDIRECT_STATUS' => Request::val('REDIRECT_STATUS', ''),
		'REDIRECT_QUERY_STRING' => Request::val('REDIRECT_QUERY_STRING', ''),
		'HTTP_CONNECTION' => Request::val('HTTP_CONNECTION', ''),
		'CONTENT_TYPE' => Request::val('CONTENT_TYPE', ''),
		'CONTENT_LENGTH' => Request::val('CONTENT_LENGTH', ''),
		'UNIQUE_ID' => Request::val('UNIQUE_ID', ''),
		'SSL_SESSION_ID' => Request::val('SSL_SESSION_ID', ''),
		'HTTP_X_REQUESTED_WITH' => Request::val('HTTP_X_REQUESTED_WITH', ''),
		'HTTP_ORIGIN' => Request::val('HTTP_ORIGIN', ''),
	];


	// hook: system_cookies_before_insert
	if(function_exists('system_cookies_before_insert')) {
		$args = [];
		if(!system_cookies_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('system_cookies', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('system_cookies', $recID, calculated_fields()['system_cookies']);

	// hook: system_cookies_after_insert
	if(function_exists('system_cookies_after_insert')) {
		$res = sql("SELECT * FROM `system_cookies` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!system_cookies_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('system_cookies', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) system_cookies_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function system_cookies_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function system_cookies_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('system_cookies', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: system_cookies_before_delete
	if(function_exists('system_cookies_before_delete')) {
		$args = [];
		if(!system_cookies_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `system_cookies` WHERE `id`='{$selected_id}'", $eo);

	// hook: system_cookies_after_delete
	if(function_exists('system_cookies_after_delete')) {
		$args = [];
		system_cookies_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='system_cookies' AND `pkValue`='{$selected_id}'", $eo);
}

function system_cookies_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('system_cookies', $selected_id, 'edit')) return false;

	$data = [
		'PATH' => Request::val('PATH', ''),
		'HTTP_ACCEPT' => Request::val('HTTP_ACCEPT', ''),
		'HTTP_ACCEPT_ENCODING' => Request::val('HTTP_ACCEPT_ENCODING', ''),
		'HTTP_ACCEPT_LANGUAGE' => Request::val('HTTP_ACCEPT_LANGUAGE', ''),
		'HTTP_COOKIE' => Request::val('HTTP_COOKIE', ''),
		'HTTP_HOST' => Request::val('HTTP_HOST', ''),
		'HTTP_USER_AGENT' => Request::val('HTTP_USER_AGENT', ''),
		'HTTP_CACHE_CONTROL' => Request::val('HTTP_CACHE_CONTROL', ''),
		'HTTP_SEC_CH_UA' => Request::val('HTTP_SEC_CH_UA', ''),
		'HTTP_SEC_CH_UA_MOBILE' => Request::val('HTTP_SEC_CH_UA_MOBILE', ''),
		'HTTP_SEC_CH_UA_PLATFORM' => Request::val('HTTP_SEC_CH_UA_PLATFORM', ''),
		'HTTP_UPGRADE_INSECURE_REQUESTS' => Request::val('HTTP_UPGRADE_INSECURE_REQUESTS', ''),
		'HTTP_SEC_FETCH_SITE' => Request::val('HTTP_SEC_FETCH_SITE', ''),
		'HTTP_SEC_FETCH_MODE' => Request::val('HTTP_SEC_FETCH_MODE', ''),
		'HTTP_SEC_FETCH_USER' => Request::val('HTTP_SEC_FETCH_USER', ''),
		'HTTP_SEC_FETCH_DEST' => Request::val('HTTP_SEC_FETCH_DEST', ''),
		'HTTP_X_HTTPS' => Request::val('HTTP_X_HTTPS', ''),
		'DOCUMENT_ROOT' => Request::val('DOCUMENT_ROOT', ''),
		'REMOTE_ADDR' => Request::val('REMOTE_ADDR', ''),
		'REMOTE_PORT' => Request::val('REMOTE_PORT', ''),
		'SERVER_ADDR' => Request::val('SERVER_ADDR', ''),
		'SERVER_NAME' => Request::val('SERVER_NAME', ''),
		'SERVER_ADMIN' => Request::val('SERVER_ADMIN', ''),
		'SERVER_PORT' => Request::val('SERVER_PORT', ''),
		'REQUEST_SCHEME' => Request::val('REQUEST_SCHEME', ''),
		'REQUEST_URI' => Request::val('REQUEST_URI', ''),
		'GEOIP_ADDR' => Request::val('GEOIP_ADDR', ''),
		'GEOIP_CONTINENT_CODE' => Request::val('GEOIP_CONTINENT_CODE', ''),
		'GEOIP_COUNTRY_CODE' => Request::val('GEOIP_COUNTRY_CODE', ''),
		'GEOIP_COUNTRY_NAME' => Request::val('GEOIP_COUNTRY_NAME', ''),
		'GEOIP_CITY' => Request::val('GEOIP_CITY', ''),
		'GEOIP_CITY_CONTINENT_CODE' => Request::val('GEOIP_CITY_CONTINENT_CODE', ''),
		'GEOIP_CITY_COUNTRY_CODE' => Request::val('GEOIP_CITY_COUNTRY_CODE', ''),
		'GEOIP_CITY_COUNTRY_NAME' => Request::val('GEOIP_CITY_COUNTRY_NAME', ''),
		'GEOIP_REGION' => Request::val('GEOIP_REGION', ''),
		'GEOIP_LATITUDE' => Request::val('GEOIP_LATITUDE', ''),
		'GEOIP_LONGITUDE' => Request::val('GEOIP_LONGITUDE', ''),
		'GEOIP_ISP' => Request::val('GEOIP_ISP', ''),
		'GEOIP_ORGANIZATION' => Request::val('GEOIP_ORGANIZATION', ''),
		'GEOIP_POSTAL_CODE' => Request::val('GEOIP_POSTAL_CODE', ''),
		'GEOIP_DMA_CODE' => Request::val('GEOIP_DMA_CODE', ''),
		'HTTPS' => Request::val('HTTPS', ''),
		'CRAWLER_USLEEP' => Request::val('CRAWLER_USLEEP', ''),
		'CRAWLER_LOAD_LIMIT_ENFORCE' => Request::val('CRAWLER_LOAD_LIMIT_ENFORCE', ''),
		'X_SPDY' => Request::val('X_SPDY', ''),
		'SSL_PROTOCOL' => Request::val('SSL_PROTOCOL', ''),
		'SSL_CIPHER' => Request::val('SSL_CIPHER', ''),
		'SSL_CIPHER_USEKEYSIZE' => Request::val('SSL_CIPHER_USEKEYSIZE', ''),
		'SSL_CIPHER_ALGKEYSIZE' => Request::val('SSL_CIPHER_ALGKEYSIZE', ''),
		'SCRIPT_FILENAME' => Request::val('SCRIPT_FILENAME', ''),
		'QUERY_STRING' => Request::val('QUERY_STRING', ''),
		'SCRIPT_URI' => Request::val('SCRIPT_URI', ''),
		'SCRIPT_URL' => Request::val('SCRIPT_URL', ''),
		'SCRIPT_NAME' => Request::val('SCRIPT_NAME', ''),
		'SERVER_PROTOCOL' => Request::val('SERVER_PROTOCOL', ''),
		'SERVER_SOFTWARE' => Request::val('SERVER_SOFTWARE', ''),
		'REQUEST_METHOD' => Request::val('REQUEST_METHOD', ''),
		'PHP_SELF' => Request::val('PHP_SELF', ''),
		'REQUEST_TIME_FLOAT' => Request::val('REQUEST_TIME_FLOAT', ''),
		'REQUEST_TIME' => Request::val('REQUEST_TIME', ''),
		'HTTP_REFERER' => Request::val('HTTP_REFERER', ''),
		'REDIRECT_URL' => Request::val('REDIRECT_URL', ''),
		'REDIRECT_REQUEST_METHOD' => Request::val('REDIRECT_REQUEST_METHOD', ''),
		'REDIRECT_STATUS' => Request::val('REDIRECT_STATUS', ''),
		'REDIRECT_QUERY_STRING' => Request::val('REDIRECT_QUERY_STRING', ''),
		'HTTP_CONNECTION' => Request::val('HTTP_CONNECTION', ''),
		'CONTENT_TYPE' => Request::val('CONTENT_TYPE', ''),
		'CONTENT_LENGTH' => Request::val('CONTENT_LENGTH', ''),
		'UNIQUE_ID' => Request::val('UNIQUE_ID', ''),
		'SSL_SESSION_ID' => Request::val('SSL_SESSION_ID', ''),
		'HTTP_X_REQUESTED_WITH' => Request::val('HTTP_X_REQUESTED_WITH', ''),
		'HTTP_ORIGIN' => Request::val('HTTP_ORIGIN', ''),
	];

	// get existing values
	$old_data = getRecord('system_cookies', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: system_cookies_before_update
	if(function_exists('system_cookies_before_update')) {
		$args = ['old_data' => $old_data];
		if(!system_cookies_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'system_cookies', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="system_cookies_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('system_cookies', $data['selectedID'], calculated_fields()['system_cookies']);

	// hook: system_cookies_after_update
	if(function_exists('system_cookies_after_update')) {
		$res = sql("SELECT * FROM `system_cookies` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!system_cookies_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='system_cookies' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function system_cookies_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('system_cookies');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='system_cookies' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='system_cookies' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `system_cookies` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'system_cookies_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/system_cookies_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/system_cookies_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return system_cookies_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return system_cookies_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return system_cookies_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#PATH').replaceWith('<div class=\"form-control-static\" id=\"PATH\">' + (jQuery('#PATH').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_ACCEPT').replaceWith('<div class=\"form-control-static\" id=\"HTTP_ACCEPT\">' + (jQuery('#HTTP_ACCEPT').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_ACCEPT_ENCODING').replaceWith('<div class=\"form-control-static\" id=\"HTTP_ACCEPT_ENCODING\">' + (jQuery('#HTTP_ACCEPT_ENCODING').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_ACCEPT_LANGUAGE').replaceWith('<div class=\"form-control-static\" id=\"HTTP_ACCEPT_LANGUAGE\">' + (jQuery('#HTTP_ACCEPT_LANGUAGE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_COOKIE').replaceWith('<div class=\"form-control-static\" id=\"HTTP_COOKIE\">' + (jQuery('#HTTP_COOKIE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_HOST').replaceWith('<div class=\"form-control-static\" id=\"HTTP_HOST\">' + (jQuery('#HTTP_HOST').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_USER_AGENT').replaceWith('<div class=\"form-control-static\" id=\"HTTP_USER_AGENT\">' + (jQuery('#HTTP_USER_AGENT').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_CACHE_CONTROL').replaceWith('<div class=\"form-control-static\" id=\"HTTP_CACHE_CONTROL\">' + (jQuery('#HTTP_CACHE_CONTROL').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_SEC_CH_UA').replaceWith('<div class=\"form-control-static\" id=\"HTTP_SEC_CH_UA\">' + (jQuery('#HTTP_SEC_CH_UA').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_SEC_CH_UA_MOBILE').replaceWith('<div class=\"form-control-static\" id=\"HTTP_SEC_CH_UA_MOBILE\">' + (jQuery('#HTTP_SEC_CH_UA_MOBILE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_SEC_CH_UA_PLATFORM').replaceWith('<div class=\"form-control-static\" id=\"HTTP_SEC_CH_UA_PLATFORM\">' + (jQuery('#HTTP_SEC_CH_UA_PLATFORM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_UPGRADE_INSECURE_REQUESTS').replaceWith('<div class=\"form-control-static\" id=\"HTTP_UPGRADE_INSECURE_REQUESTS\">' + (jQuery('#HTTP_UPGRADE_INSECURE_REQUESTS').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_SEC_FETCH_SITE').replaceWith('<div class=\"form-control-static\" id=\"HTTP_SEC_FETCH_SITE\">' + (jQuery('#HTTP_SEC_FETCH_SITE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_SEC_FETCH_MODE').replaceWith('<div class=\"form-control-static\" id=\"HTTP_SEC_FETCH_MODE\">' + (jQuery('#HTTP_SEC_FETCH_MODE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_SEC_FETCH_USER').replaceWith('<div class=\"form-control-static\" id=\"HTTP_SEC_FETCH_USER\">' + (jQuery('#HTTP_SEC_FETCH_USER').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_SEC_FETCH_DEST').replaceWith('<div class=\"form-control-static\" id=\"HTTP_SEC_FETCH_DEST\">' + (jQuery('#HTTP_SEC_FETCH_DEST').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_X_HTTPS').replaceWith('<div class=\"form-control-static\" id=\"HTTP_X_HTTPS\">' + (jQuery('#HTTP_X_HTTPS').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#DOCUMENT_ROOT').replaceWith('<div class=\"form-control-static\" id=\"DOCUMENT_ROOT\">' + (jQuery('#DOCUMENT_ROOT').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REMOTE_ADDR').replaceWith('<div class=\"form-control-static\" id=\"REMOTE_ADDR\">' + (jQuery('#REMOTE_ADDR').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REMOTE_PORT').replaceWith('<div class=\"form-control-static\" id=\"REMOTE_PORT\">' + (jQuery('#REMOTE_PORT').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SERVER_ADDR').replaceWith('<div class=\"form-control-static\" id=\"SERVER_ADDR\">' + (jQuery('#SERVER_ADDR').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SERVER_NAME').replaceWith('<div class=\"form-control-static\" id=\"SERVER_NAME\">' + (jQuery('#SERVER_NAME').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SERVER_ADMIN').replaceWith('<div class=\"form-control-static\" id=\"SERVER_ADMIN\">' + (jQuery('#SERVER_ADMIN').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SERVER_PORT').replaceWith('<div class=\"form-control-static\" id=\"SERVER_PORT\">' + (jQuery('#SERVER_PORT').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REQUEST_SCHEME').replaceWith('<div class=\"form-control-static\" id=\"REQUEST_SCHEME\">' + (jQuery('#REQUEST_SCHEME').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REQUEST_URI').replaceWith('<div class=\"form-control-static\" id=\"REQUEST_URI\">' + (jQuery('#REQUEST_URI').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_ADDR').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_ADDR\">' + (jQuery('#GEOIP_ADDR').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_CONTINENT_CODE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_CONTINENT_CODE\">' + (jQuery('#GEOIP_CONTINENT_CODE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_COUNTRY_CODE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_COUNTRY_CODE\">' + (jQuery('#GEOIP_COUNTRY_CODE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_COUNTRY_NAME').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_COUNTRY_NAME\">' + (jQuery('#GEOIP_COUNTRY_NAME').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_CITY').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_CITY\">' + (jQuery('#GEOIP_CITY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_CITY_CONTINENT_CODE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_CITY_CONTINENT_CODE\">' + (jQuery('#GEOIP_CITY_CONTINENT_CODE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_CITY_COUNTRY_CODE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_CITY_COUNTRY_CODE\">' + (jQuery('#GEOIP_CITY_COUNTRY_CODE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_CITY_COUNTRY_NAME').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_CITY_COUNTRY_NAME\">' + (jQuery('#GEOIP_CITY_COUNTRY_NAME').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_REGION').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_REGION\">' + (jQuery('#GEOIP_REGION').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_LATITUDE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_LATITUDE\">' + (jQuery('#GEOIP_LATITUDE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_LONGITUDE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_LONGITUDE\">' + (jQuery('#GEOIP_LONGITUDE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_ISP').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_ISP\">' + (jQuery('#GEOIP_ISP').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_ORGANIZATION').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_ORGANIZATION\">' + (jQuery('#GEOIP_ORGANIZATION').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_POSTAL_CODE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_POSTAL_CODE\">' + (jQuery('#GEOIP_POSTAL_CODE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#GEOIP_DMA_CODE').replaceWith('<div class=\"form-control-static\" id=\"GEOIP_DMA_CODE\">' + (jQuery('#GEOIP_DMA_CODE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTPS').replaceWith('<div class=\"form-control-static\" id=\"HTTPS\">' + (jQuery('#HTTPS').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CRAWLER_USLEEP').replaceWith('<div class=\"form-control-static\" id=\"CRAWLER_USLEEP\">' + (jQuery('#CRAWLER_USLEEP').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CRAWLER_LOAD_LIMIT_ENFORCE').replaceWith('<div class=\"form-control-static\" id=\"CRAWLER_LOAD_LIMIT_ENFORCE\">' + (jQuery('#CRAWLER_LOAD_LIMIT_ENFORCE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#X_SPDY').replaceWith('<div class=\"form-control-static\" id=\"X_SPDY\">' + (jQuery('#X_SPDY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SSL_PROTOCOL').replaceWith('<div class=\"form-control-static\" id=\"SSL_PROTOCOL\">' + (jQuery('#SSL_PROTOCOL').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SSL_CIPHER').replaceWith('<div class=\"form-control-static\" id=\"SSL_CIPHER\">' + (jQuery('#SSL_CIPHER').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SSL_CIPHER_USEKEYSIZE').replaceWith('<div class=\"form-control-static\" id=\"SSL_CIPHER_USEKEYSIZE\">' + (jQuery('#SSL_CIPHER_USEKEYSIZE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SSL_CIPHER_ALGKEYSIZE').replaceWith('<div class=\"form-control-static\" id=\"SSL_CIPHER_ALGKEYSIZE\">' + (jQuery('#SSL_CIPHER_ALGKEYSIZE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SCRIPT_FILENAME').replaceWith('<div class=\"form-control-static\" id=\"SCRIPT_FILENAME\">' + (jQuery('#SCRIPT_FILENAME').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#QUERY_STRING').replaceWith('<div class=\"form-control-static\" id=\"QUERY_STRING\">' + (jQuery('#QUERY_STRING').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SCRIPT_URI').replaceWith('<div class=\"form-control-static\" id=\"SCRIPT_URI\">' + (jQuery('#SCRIPT_URI').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SCRIPT_URL').replaceWith('<div class=\"form-control-static\" id=\"SCRIPT_URL\">' + (jQuery('#SCRIPT_URL').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SCRIPT_NAME').replaceWith('<div class=\"form-control-static\" id=\"SCRIPT_NAME\">' + (jQuery('#SCRIPT_NAME').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SERVER_PROTOCOL').replaceWith('<div class=\"form-control-static\" id=\"SERVER_PROTOCOL\">' + (jQuery('#SERVER_PROTOCOL').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SERVER_SOFTWARE').replaceWith('<div class=\"form-control-static\" id=\"SERVER_SOFTWARE\">' + (jQuery('#SERVER_SOFTWARE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REQUEST_METHOD').replaceWith('<div class=\"form-control-static\" id=\"REQUEST_METHOD\">' + (jQuery('#REQUEST_METHOD').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#PHP_SELF').replaceWith('<div class=\"form-control-static\" id=\"PHP_SELF\">' + (jQuery('#PHP_SELF').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REQUEST_TIME_FLOAT').replaceWith('<div class=\"form-control-static\" id=\"REQUEST_TIME_FLOAT\">' + (jQuery('#REQUEST_TIME_FLOAT').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REQUEST_TIME').replaceWith('<div class=\"form-control-static\" id=\"REQUEST_TIME\">' + (jQuery('#REQUEST_TIME').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_REFERER').replaceWith('<div class=\"form-control-static\" id=\"HTTP_REFERER\">' + (jQuery('#HTTP_REFERER').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REDIRECT_URL').replaceWith('<div class=\"form-control-static\" id=\"REDIRECT_URL\">' + (jQuery('#REDIRECT_URL').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REDIRECT_REQUEST_METHOD').replaceWith('<div class=\"form-control-static\" id=\"REDIRECT_REQUEST_METHOD\">' + (jQuery('#REDIRECT_REQUEST_METHOD').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REDIRECT_STATUS').replaceWith('<div class=\"form-control-static\" id=\"REDIRECT_STATUS\">' + (jQuery('#REDIRECT_STATUS').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#REDIRECT_QUERY_STRING').replaceWith('<div class=\"form-control-static\" id=\"REDIRECT_QUERY_STRING\">' + (jQuery('#REDIRECT_QUERY_STRING').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_CONNECTION').replaceWith('<div class=\"form-control-static\" id=\"HTTP_CONNECTION\">' + (jQuery('#HTTP_CONNECTION').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CONTENT_TYPE').replaceWith('<div class=\"form-control-static\" id=\"CONTENT_TYPE\">' + (jQuery('#CONTENT_TYPE').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CONTENT_LENGTH').replaceWith('<div class=\"form-control-static\" id=\"CONTENT_LENGTH\">' + (jQuery('#CONTENT_LENGTH').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#UNIQUE_ID').replaceWith('<div class=\"form-control-static\" id=\"UNIQUE_ID\">' + (jQuery('#UNIQUE_ID').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SSL_SESSION_ID').replaceWith('<div class=\"form-control-static\" id=\"SSL_SESSION_ID\">' + (jQuery('#SSL_SESSION_ID').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_X_REQUESTED_WITH').replaceWith('<div class=\"form-control-static\" id=\"HTTP_X_REQUESTED_WITH\">' + (jQuery('#HTTP_X_REQUESTED_WITH').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HTTP_ORIGIN').replaceWith('<div class=\"form-control-static\" id=\"HTTP_ORIGIN\">' + (jQuery('#HTTP_ORIGIN').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(PATH)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_ACCEPT)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_ACCEPT_ENCODING)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_ACCEPT_LANGUAGE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_COOKIE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_HOST)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_USER_AGENT)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_CACHE_CONTROL)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_SEC_CH_UA)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_SEC_CH_UA_MOBILE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_SEC_CH_UA_PLATFORM)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_UPGRADE_INSECURE_REQUESTS)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_SEC_FETCH_SITE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_SEC_FETCH_MODE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_SEC_FETCH_USER)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_SEC_FETCH_DEST)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_X_HTTPS)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DOCUMENT_ROOT)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REMOTE_ADDR)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REMOTE_PORT)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SERVER_ADDR)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SERVER_NAME)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SERVER_ADMIN)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SERVER_PORT)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REQUEST_SCHEME)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REQUEST_URI)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_ADDR)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_CONTINENT_CODE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_COUNTRY_CODE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_COUNTRY_NAME)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_CITY)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_CITY_CONTINENT_CODE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_CITY_COUNTRY_CODE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_CITY_COUNTRY_NAME)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_REGION)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_LATITUDE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_LONGITUDE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_ISP)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_ORGANIZATION)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_POSTAL_CODE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(GEOIP_DMA_CODE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTPS)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CRAWLER_USLEEP)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CRAWLER_LOAD_LIMIT_ENFORCE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(X_SPDY)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SSL_PROTOCOL)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SSL_CIPHER)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SSL_CIPHER_USEKEYSIZE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SSL_CIPHER_ALGKEYSIZE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SCRIPT_FILENAME)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(QUERY_STRING)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SCRIPT_URI)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SCRIPT_URL)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SCRIPT_NAME)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SERVER_PROTOCOL)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SERVER_SOFTWARE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REQUEST_METHOD)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(PHP_SELF)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REQUEST_TIME_FLOAT)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REQUEST_TIME)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_REFERER)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REDIRECT_URL)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REDIRECT_REQUEST_METHOD)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REDIRECT_STATUS)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(REDIRECT_QUERY_STRING)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_CONNECTION)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CONTENT_TYPE)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CONTENT_LENGTH)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(UNIQUE_ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SSL_SESSION_ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_X_REQUESTED_WITH)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HTTP_ORIGIN)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(PATH)%%>', safe_html($urow['PATH']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(PATH)%%>', html_attr($row['PATH']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PATH)%%>', urlencode($urow['PATH']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ACCEPT)%%>', safe_html($urow['HTTP_ACCEPT']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ACCEPT)%%>', html_attr($row['HTTP_ACCEPT']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ACCEPT)%%>', urlencode($urow['HTTP_ACCEPT']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ACCEPT_ENCODING)%%>', safe_html($urow['HTTP_ACCEPT_ENCODING']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ACCEPT_ENCODING)%%>', html_attr($row['HTTP_ACCEPT_ENCODING']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ACCEPT_ENCODING)%%>', urlencode($urow['HTTP_ACCEPT_ENCODING']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ACCEPT_LANGUAGE)%%>', safe_html($urow['HTTP_ACCEPT_LANGUAGE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ACCEPT_LANGUAGE)%%>', html_attr($row['HTTP_ACCEPT_LANGUAGE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ACCEPT_LANGUAGE)%%>', urlencode($urow['HTTP_ACCEPT_LANGUAGE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_COOKIE)%%>', safe_html($urow['HTTP_COOKIE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_COOKIE)%%>', html_attr($row['HTTP_COOKIE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_COOKIE)%%>', urlencode($urow['HTTP_COOKIE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_HOST)%%>', safe_html($urow['HTTP_HOST']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_HOST)%%>', html_attr($row['HTTP_HOST']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_HOST)%%>', urlencode($urow['HTTP_HOST']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_USER_AGENT)%%>', safe_html($urow['HTTP_USER_AGENT']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_USER_AGENT)%%>', html_attr($row['HTTP_USER_AGENT']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_USER_AGENT)%%>', urlencode($urow['HTTP_USER_AGENT']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_CACHE_CONTROL)%%>', safe_html($urow['HTTP_CACHE_CONTROL']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_CACHE_CONTROL)%%>', html_attr($row['HTTP_CACHE_CONTROL']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_CACHE_CONTROL)%%>', urlencode($urow['HTTP_CACHE_CONTROL']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA)%%>', safe_html($urow['HTTP_SEC_CH_UA']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA)%%>', html_attr($row['HTTP_SEC_CH_UA']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_CH_UA)%%>', urlencode($urow['HTTP_SEC_CH_UA']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA_MOBILE)%%>', safe_html($urow['HTTP_SEC_CH_UA_MOBILE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA_MOBILE)%%>', html_attr($row['HTTP_SEC_CH_UA_MOBILE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_CH_UA_MOBILE)%%>', urlencode($urow['HTTP_SEC_CH_UA_MOBILE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA_PLATFORM)%%>', safe_html($urow['HTTP_SEC_CH_UA_PLATFORM']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA_PLATFORM)%%>', html_attr($row['HTTP_SEC_CH_UA_PLATFORM']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_CH_UA_PLATFORM)%%>', urlencode($urow['HTTP_SEC_CH_UA_PLATFORM']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_UPGRADE_INSECURE_REQUESTS)%%>', safe_html($urow['HTTP_UPGRADE_INSECURE_REQUESTS']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_UPGRADE_INSECURE_REQUESTS)%%>', html_attr($row['HTTP_UPGRADE_INSECURE_REQUESTS']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_UPGRADE_INSECURE_REQUESTS)%%>', urlencode($urow['HTTP_UPGRADE_INSECURE_REQUESTS']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_SITE)%%>', safe_html($urow['HTTP_SEC_FETCH_SITE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_SITE)%%>', html_attr($row['HTTP_SEC_FETCH_SITE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_SITE)%%>', urlencode($urow['HTTP_SEC_FETCH_SITE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_MODE)%%>', safe_html($urow['HTTP_SEC_FETCH_MODE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_MODE)%%>', html_attr($row['HTTP_SEC_FETCH_MODE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_MODE)%%>', urlencode($urow['HTTP_SEC_FETCH_MODE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_USER)%%>', safe_html($urow['HTTP_SEC_FETCH_USER']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_USER)%%>', html_attr($row['HTTP_SEC_FETCH_USER']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_USER)%%>', urlencode($urow['HTTP_SEC_FETCH_USER']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_DEST)%%>', safe_html($urow['HTTP_SEC_FETCH_DEST']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_DEST)%%>', html_attr($row['HTTP_SEC_FETCH_DEST']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_DEST)%%>', urlencode($urow['HTTP_SEC_FETCH_DEST']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_X_HTTPS)%%>', safe_html($urow['HTTP_X_HTTPS']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_X_HTTPS)%%>', html_attr($row['HTTP_X_HTTPS']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_X_HTTPS)%%>', urlencode($urow['HTTP_X_HTTPS']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(DOCUMENT_ROOT)%%>', safe_html($urow['DOCUMENT_ROOT']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(DOCUMENT_ROOT)%%>', html_attr($row['DOCUMENT_ROOT']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DOCUMENT_ROOT)%%>', urlencode($urow['DOCUMENT_ROOT']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REMOTE_ADDR)%%>', safe_html($urow['REMOTE_ADDR']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REMOTE_ADDR)%%>', html_attr($row['REMOTE_ADDR']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REMOTE_ADDR)%%>', urlencode($urow['REMOTE_ADDR']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REMOTE_PORT)%%>', safe_html($urow['REMOTE_PORT']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REMOTE_PORT)%%>', html_attr($row['REMOTE_PORT']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REMOTE_PORT)%%>', urlencode($urow['REMOTE_PORT']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SERVER_ADDR)%%>', safe_html($urow['SERVER_ADDR']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SERVER_ADDR)%%>', html_attr($row['SERVER_ADDR']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_ADDR)%%>', urlencode($urow['SERVER_ADDR']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SERVER_NAME)%%>', safe_html($urow['SERVER_NAME']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SERVER_NAME)%%>', html_attr($row['SERVER_NAME']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_NAME)%%>', urlencode($urow['SERVER_NAME']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SERVER_ADMIN)%%>', safe_html($urow['SERVER_ADMIN']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SERVER_ADMIN)%%>', html_attr($row['SERVER_ADMIN']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_ADMIN)%%>', urlencode($urow['SERVER_ADMIN']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SERVER_PORT)%%>', safe_html($urow['SERVER_PORT']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SERVER_PORT)%%>', html_attr($row['SERVER_PORT']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_PORT)%%>', urlencode($urow['SERVER_PORT']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_SCHEME)%%>', safe_html($urow['REQUEST_SCHEME']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_SCHEME)%%>', html_attr($row['REQUEST_SCHEME']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_SCHEME)%%>', urlencode($urow['REQUEST_SCHEME']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_URI)%%>', safe_html($urow['REQUEST_URI']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_URI)%%>', html_attr($row['REQUEST_URI']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_URI)%%>', urlencode($urow['REQUEST_URI']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_ADDR)%%>', safe_html($urow['GEOIP_ADDR']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_ADDR)%%>', html_attr($row['GEOIP_ADDR']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_ADDR)%%>', urlencode($urow['GEOIP_ADDR']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CONTINENT_CODE)%%>', safe_html($urow['GEOIP_CONTINENT_CODE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CONTINENT_CODE)%%>', html_attr($row['GEOIP_CONTINENT_CODE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CONTINENT_CODE)%%>', urlencode($urow['GEOIP_CONTINENT_CODE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_COUNTRY_CODE)%%>', safe_html($urow['GEOIP_COUNTRY_CODE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_COUNTRY_CODE)%%>', html_attr($row['GEOIP_COUNTRY_CODE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_COUNTRY_CODE)%%>', urlencode($urow['GEOIP_COUNTRY_CODE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_COUNTRY_NAME)%%>', safe_html($urow['GEOIP_COUNTRY_NAME']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_COUNTRY_NAME)%%>', html_attr($row['GEOIP_COUNTRY_NAME']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_COUNTRY_NAME)%%>', urlencode($urow['GEOIP_COUNTRY_NAME']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY)%%>', safe_html($urow['GEOIP_CITY']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY)%%>', html_attr($row['GEOIP_CITY']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY)%%>', urlencode($urow['GEOIP_CITY']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY_CONTINENT_CODE)%%>', safe_html($urow['GEOIP_CITY_CONTINENT_CODE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY_CONTINENT_CODE)%%>', html_attr($row['GEOIP_CITY_CONTINENT_CODE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY_CONTINENT_CODE)%%>', urlencode($urow['GEOIP_CITY_CONTINENT_CODE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY_COUNTRY_CODE)%%>', safe_html($urow['GEOIP_CITY_COUNTRY_CODE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY_COUNTRY_CODE)%%>', html_attr($row['GEOIP_CITY_COUNTRY_CODE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY_COUNTRY_CODE)%%>', urlencode($urow['GEOIP_CITY_COUNTRY_CODE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY_COUNTRY_NAME)%%>', safe_html($urow['GEOIP_CITY_COUNTRY_NAME']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_CITY_COUNTRY_NAME)%%>', html_attr($row['GEOIP_CITY_COUNTRY_NAME']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY_COUNTRY_NAME)%%>', urlencode($urow['GEOIP_CITY_COUNTRY_NAME']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_REGION)%%>', safe_html($urow['GEOIP_REGION']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_REGION)%%>', html_attr($row['GEOIP_REGION']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_REGION)%%>', urlencode($urow['GEOIP_REGION']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_LATITUDE)%%>', safe_html($urow['GEOIP_LATITUDE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_LATITUDE)%%>', html_attr($row['GEOIP_LATITUDE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_LATITUDE)%%>', urlencode($urow['GEOIP_LATITUDE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_LONGITUDE)%%>', safe_html($urow['GEOIP_LONGITUDE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_LONGITUDE)%%>', html_attr($row['GEOIP_LONGITUDE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_LONGITUDE)%%>', urlencode($urow['GEOIP_LONGITUDE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_ISP)%%>', safe_html($urow['GEOIP_ISP']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_ISP)%%>', html_attr($row['GEOIP_ISP']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_ISP)%%>', urlencode($urow['GEOIP_ISP']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_ORGANIZATION)%%>', safe_html($urow['GEOIP_ORGANIZATION']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_ORGANIZATION)%%>', html_attr($row['GEOIP_ORGANIZATION']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_ORGANIZATION)%%>', urlencode($urow['GEOIP_ORGANIZATION']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_POSTAL_CODE)%%>', safe_html($urow['GEOIP_POSTAL_CODE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_POSTAL_CODE)%%>', html_attr($row['GEOIP_POSTAL_CODE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_POSTAL_CODE)%%>', urlencode($urow['GEOIP_POSTAL_CODE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_DMA_CODE)%%>', safe_html($urow['GEOIP_DMA_CODE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(GEOIP_DMA_CODE)%%>', html_attr($row['GEOIP_DMA_CODE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_DMA_CODE)%%>', urlencode($urow['GEOIP_DMA_CODE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTPS)%%>', safe_html($urow['HTTPS']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTPS)%%>', html_attr($row['HTTPS']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTPS)%%>', urlencode($urow['HTTPS']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CRAWLER_USLEEP)%%>', safe_html($urow['CRAWLER_USLEEP']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CRAWLER_USLEEP)%%>', html_attr($row['CRAWLER_USLEEP']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CRAWLER_USLEEP)%%>', urlencode($urow['CRAWLER_USLEEP']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CRAWLER_LOAD_LIMIT_ENFORCE)%%>', safe_html($urow['CRAWLER_LOAD_LIMIT_ENFORCE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CRAWLER_LOAD_LIMIT_ENFORCE)%%>', html_attr($row['CRAWLER_LOAD_LIMIT_ENFORCE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CRAWLER_LOAD_LIMIT_ENFORCE)%%>', urlencode($urow['CRAWLER_LOAD_LIMIT_ENFORCE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(X_SPDY)%%>', safe_html($urow['X_SPDY']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(X_SPDY)%%>', html_attr($row['X_SPDY']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(X_SPDY)%%>', urlencode($urow['X_SPDY']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SSL_PROTOCOL)%%>', safe_html($urow['SSL_PROTOCOL']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SSL_PROTOCOL)%%>', html_attr($row['SSL_PROTOCOL']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_PROTOCOL)%%>', urlencode($urow['SSL_PROTOCOL']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SSL_CIPHER)%%>', safe_html($urow['SSL_CIPHER']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SSL_CIPHER)%%>', html_attr($row['SSL_CIPHER']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_CIPHER)%%>', urlencode($urow['SSL_CIPHER']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SSL_CIPHER_USEKEYSIZE)%%>', safe_html($urow['SSL_CIPHER_USEKEYSIZE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SSL_CIPHER_USEKEYSIZE)%%>', html_attr($row['SSL_CIPHER_USEKEYSIZE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_CIPHER_USEKEYSIZE)%%>', urlencode($urow['SSL_CIPHER_USEKEYSIZE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SSL_CIPHER_ALGKEYSIZE)%%>', safe_html($urow['SSL_CIPHER_ALGKEYSIZE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SSL_CIPHER_ALGKEYSIZE)%%>', html_attr($row['SSL_CIPHER_ALGKEYSIZE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_CIPHER_ALGKEYSIZE)%%>', urlencode($urow['SSL_CIPHER_ALGKEYSIZE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_FILENAME)%%>', safe_html($urow['SCRIPT_FILENAME']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_FILENAME)%%>', html_attr($row['SCRIPT_FILENAME']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_FILENAME)%%>', urlencode($urow['SCRIPT_FILENAME']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(QUERY_STRING)%%>', safe_html($urow['QUERY_STRING']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(QUERY_STRING)%%>', html_attr($row['QUERY_STRING']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(QUERY_STRING)%%>', urlencode($urow['QUERY_STRING']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_URI)%%>', safe_html($urow['SCRIPT_URI']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_URI)%%>', html_attr($row['SCRIPT_URI']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_URI)%%>', urlencode($urow['SCRIPT_URI']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_URL)%%>', safe_html($urow['SCRIPT_URL']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_URL)%%>', html_attr($row['SCRIPT_URL']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_URL)%%>', urlencode($urow['SCRIPT_URL']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_NAME)%%>', safe_html($urow['SCRIPT_NAME']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SCRIPT_NAME)%%>', html_attr($row['SCRIPT_NAME']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_NAME)%%>', urlencode($urow['SCRIPT_NAME']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SERVER_PROTOCOL)%%>', safe_html($urow['SERVER_PROTOCOL']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SERVER_PROTOCOL)%%>', html_attr($row['SERVER_PROTOCOL']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_PROTOCOL)%%>', urlencode($urow['SERVER_PROTOCOL']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SERVER_SOFTWARE)%%>', safe_html($urow['SERVER_SOFTWARE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SERVER_SOFTWARE)%%>', html_attr($row['SERVER_SOFTWARE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_SOFTWARE)%%>', urlencode($urow['SERVER_SOFTWARE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_METHOD)%%>', safe_html($urow['REQUEST_METHOD']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_METHOD)%%>', html_attr($row['REQUEST_METHOD']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_METHOD)%%>', urlencode($urow['REQUEST_METHOD']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(PHP_SELF)%%>', safe_html($urow['PHP_SELF']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(PHP_SELF)%%>', html_attr($row['PHP_SELF']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PHP_SELF)%%>', urlencode($urow['PHP_SELF']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_TIME_FLOAT)%%>', safe_html($urow['REQUEST_TIME_FLOAT']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_TIME_FLOAT)%%>', html_attr($row['REQUEST_TIME_FLOAT']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_TIME_FLOAT)%%>', urlencode($urow['REQUEST_TIME_FLOAT']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_TIME)%%>', safe_html($urow['REQUEST_TIME']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REQUEST_TIME)%%>', html_attr($row['REQUEST_TIME']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_TIME)%%>', urlencode($urow['REQUEST_TIME']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_REFERER)%%>', safe_html($urow['HTTP_REFERER']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_REFERER)%%>', html_attr($row['HTTP_REFERER']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_REFERER)%%>', urlencode($urow['HTTP_REFERER']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_URL)%%>', safe_html($urow['REDIRECT_URL']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_URL)%%>', html_attr($row['REDIRECT_URL']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_URL)%%>', urlencode($urow['REDIRECT_URL']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_REQUEST_METHOD)%%>', safe_html($urow['REDIRECT_REQUEST_METHOD']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_REQUEST_METHOD)%%>', html_attr($row['REDIRECT_REQUEST_METHOD']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_REQUEST_METHOD)%%>', urlencode($urow['REDIRECT_REQUEST_METHOD']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_STATUS)%%>', safe_html($urow['REDIRECT_STATUS']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_STATUS)%%>', html_attr($row['REDIRECT_STATUS']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_STATUS)%%>', urlencode($urow['REDIRECT_STATUS']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_QUERY_STRING)%%>', safe_html($urow['REDIRECT_QUERY_STRING']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(REDIRECT_QUERY_STRING)%%>', html_attr($row['REDIRECT_QUERY_STRING']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_QUERY_STRING)%%>', urlencode($urow['REDIRECT_QUERY_STRING']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_CONNECTION)%%>', safe_html($urow['HTTP_CONNECTION']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_CONNECTION)%%>', html_attr($row['HTTP_CONNECTION']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_CONNECTION)%%>', urlencode($urow['HTTP_CONNECTION']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CONTENT_TYPE)%%>', safe_html($urow['CONTENT_TYPE']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CONTENT_TYPE)%%>', html_attr($row['CONTENT_TYPE']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CONTENT_TYPE)%%>', urlencode($urow['CONTENT_TYPE']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CONTENT_LENGTH)%%>', safe_html($urow['CONTENT_LENGTH']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CONTENT_LENGTH)%%>', html_attr($row['CONTENT_LENGTH']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CONTENT_LENGTH)%%>', urlencode($urow['CONTENT_LENGTH']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(UNIQUE_ID)%%>', safe_html($urow['UNIQUE_ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(UNIQUE_ID)%%>', html_attr($row['UNIQUE_ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(UNIQUE_ID)%%>', urlencode($urow['UNIQUE_ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SSL_SESSION_ID)%%>', safe_html($urow['SSL_SESSION_ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SSL_SESSION_ID)%%>', html_attr($row['SSL_SESSION_ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_SESSION_ID)%%>', urlencode($urow['SSL_SESSION_ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_X_REQUESTED_WITH)%%>', safe_html($urow['HTTP_X_REQUESTED_WITH']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_X_REQUESTED_WITH)%%>', html_attr($row['HTTP_X_REQUESTED_WITH']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_X_REQUESTED_WITH)%%>', urlencode($urow['HTTP_X_REQUESTED_WITH']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ORIGIN)%%>', safe_html($urow['HTTP_ORIGIN']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HTTP_ORIGIN)%%>', html_attr($row['HTTP_ORIGIN']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ORIGIN)%%>', urlencode($urow['HTTP_ORIGIN']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(PATH)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PATH)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_ACCEPT)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ACCEPT)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_ACCEPT_ENCODING)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ACCEPT_ENCODING)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_ACCEPT_LANGUAGE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ACCEPT_LANGUAGE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_COOKIE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_COOKIE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_HOST)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_HOST)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_USER_AGENT)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_USER_AGENT)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_CACHE_CONTROL)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_CACHE_CONTROL)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_CH_UA)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA_MOBILE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_CH_UA_MOBILE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_SEC_CH_UA_PLATFORM)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_CH_UA_PLATFORM)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_UPGRADE_INSECURE_REQUESTS)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_UPGRADE_INSECURE_REQUESTS)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_SITE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_SITE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_MODE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_MODE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_USER)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_USER)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_SEC_FETCH_DEST)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_SEC_FETCH_DEST)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_X_HTTPS)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_X_HTTPS)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DOCUMENT_ROOT)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DOCUMENT_ROOT)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REMOTE_ADDR)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REMOTE_ADDR)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REMOTE_PORT)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REMOTE_PORT)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SERVER_ADDR)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_ADDR)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SERVER_NAME)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_NAME)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SERVER_ADMIN)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_ADMIN)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SERVER_PORT)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_PORT)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REQUEST_SCHEME)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_SCHEME)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REQUEST_URI)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_URI)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_ADDR)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_ADDR)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_CONTINENT_CODE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CONTINENT_CODE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_COUNTRY_CODE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_COUNTRY_CODE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_COUNTRY_NAME)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_COUNTRY_NAME)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_CITY)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_CITY_CONTINENT_CODE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY_CONTINENT_CODE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_CITY_COUNTRY_CODE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY_COUNTRY_CODE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_CITY_COUNTRY_NAME)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_CITY_COUNTRY_NAME)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_REGION)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_REGION)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_LATITUDE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_LATITUDE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_LONGITUDE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_LONGITUDE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_ISP)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_ISP)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_ORGANIZATION)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_ORGANIZATION)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_POSTAL_CODE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_POSTAL_CODE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(GEOIP_DMA_CODE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(GEOIP_DMA_CODE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTPS)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTPS)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CRAWLER_USLEEP)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CRAWLER_USLEEP)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CRAWLER_LOAD_LIMIT_ENFORCE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CRAWLER_LOAD_LIMIT_ENFORCE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(X_SPDY)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(X_SPDY)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SSL_PROTOCOL)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_PROTOCOL)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SSL_CIPHER)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_CIPHER)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SSL_CIPHER_USEKEYSIZE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_CIPHER_USEKEYSIZE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SSL_CIPHER_ALGKEYSIZE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_CIPHER_ALGKEYSIZE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SCRIPT_FILENAME)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_FILENAME)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(QUERY_STRING)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(QUERY_STRING)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SCRIPT_URI)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_URI)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SCRIPT_URL)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_URL)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SCRIPT_NAME)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SCRIPT_NAME)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SERVER_PROTOCOL)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_PROTOCOL)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SERVER_SOFTWARE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SERVER_SOFTWARE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REQUEST_METHOD)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_METHOD)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(PHP_SELF)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PHP_SELF)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REQUEST_TIME_FLOAT)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_TIME_FLOAT)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REQUEST_TIME)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REQUEST_TIME)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_REFERER)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_REFERER)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REDIRECT_URL)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_URL)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REDIRECT_REQUEST_METHOD)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_REQUEST_METHOD)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REDIRECT_STATUS)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_STATUS)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(REDIRECT_QUERY_STRING)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(REDIRECT_QUERY_STRING)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_CONNECTION)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_CONNECTION)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CONTENT_TYPE)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CONTENT_TYPE)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CONTENT_LENGTH)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CONTENT_LENGTH)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(UNIQUE_ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(UNIQUE_ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SSL_SESSION_ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SSL_SESSION_ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_X_REQUESTED_WITH)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_X_REQUESTED_WITH)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HTTP_ORIGIN)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HTTP_ORIGIN)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('system_cookies');
	if($selected_id) {
		$jdata = get_joined_record('system_cookies', $selected_id);
		if($jdata === false) $jdata = get_defaults('system_cookies');
		$rdata = $row;
	}
	$templateCode .= loadView('system_cookies-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: system_cookies_dv
	if(function_exists('system_cookies_dv')) {
		$args = [];
		system_cookies_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}