<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/tester.php');
	include_once(__DIR__ . '/tester_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('tester');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tester';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tester`.`id`" => "id",
		"`tester`.`slot`" => "slot",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tester`.`id`',
		2 => '`tester`.`slot`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tester`.`id`" => "id",
		"`tester`.`slot`" => "slot",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tester`.`id`" => "Id",
		"`tester`.`slot`" => "Slot",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tester`.`id`" => "id",
		"`tester`.`slot`" => "slot",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`tester` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tester_view.php';
	$x->TableTitle = 'Tester';
	$x->TableIcon = 'resources/table_icons/action_log.png';
	$x->PrimaryKey = '`tester`.`id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Id', 'Slot', ];
	$x->ColFieldName = ['id', 'slot', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tester_templateTV.html';
	$x->SelectedTemplate = 'templates/tester_templateTVS.html';
	$x->TemplateDV = 'templates/tester_templateDV.html';
	$x->TemplateDVP = 'templates/tester_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tester_init
	$render = true;
	if(function_exists('tester_init')) {
		$args = [];
		$render = tester_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tester_header
	$headerCode = '';
	if(function_exists('tester_header')) {
		$args = [];
		$headerCode = tester_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tester_footer
	$footerCode = '';
	if(function_exists('tester_footer')) {
		$args = [];
		$footerCode = tester_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
