<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/tweet_factory.php');
	include_once(__DIR__ . '/tweet_factory_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('tweet_factory');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tweet_factory';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tweet_factory`.`id`" => "id",
		"`tweet_factory`.`logo`" => "logo",
		"`tweet_factory`.`file_path`" => "file_path",
		"`tweet_factory`.`execution`" => "execution",
		"`tweet_factory`.`automation`" => "automation",
		"`tweet_factory`.`category`" => "category",
		"`tweet_factory`.`title`" => "title",
		"`tweet_factory`.`description`" => "description",
		"`tweet_factory`.`author`" => "author",
		"`tweet_factory`.`user_id`" => "user_id",
		"`tweet_factory`.`status`" => "status",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tweet_factory`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`tweet_factory`.`automation`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => '`tweet_factory`.`status`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tweet_factory`.`id`" => "id",
		"`tweet_factory`.`logo`" => "logo",
		"`tweet_factory`.`file_path`" => "file_path",
		"`tweet_factory`.`execution`" => "execution",
		"`tweet_factory`.`automation`" => "automation",
		"`tweet_factory`.`category`" => "category",
		"`tweet_factory`.`title`" => "title",
		"`tweet_factory`.`description`" => "description",
		"`tweet_factory`.`author`" => "author",
		"`tweet_factory`.`user_id`" => "user_id",
		"`tweet_factory`.`status`" => "status",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tweet_factory`.`id`" => "Id",
		"`tweet_factory`.`logo`" => "Logo",
		"`tweet_factory`.`file_path`" => "File_path",
		"`tweet_factory`.`execution`" => "Execution",
		"`tweet_factory`.`automation`" => "Automation",
		"`tweet_factory`.`category`" => "Category",
		"`tweet_factory`.`title`" => "Title",
		"`tweet_factory`.`description`" => "Description",
		"`tweet_factory`.`author`" => "Author",
		"`tweet_factory`.`user_id`" => "User_id",
		"`tweet_factory`.`status`" => "Status",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tweet_factory`.`id`" => "id",
		"`tweet_factory`.`logo`" => "logo",
		"`tweet_factory`.`file_path`" => "file_path",
		"`tweet_factory`.`execution`" => "execution",
		"`tweet_factory`.`automation`" => "automation",
		"`tweet_factory`.`category`" => "category",
		"`tweet_factory`.`title`" => "title",
		"`tweet_factory`.`description`" => "description",
		"`tweet_factory`.`author`" => "author",
		"`tweet_factory`.`user_id`" => "user_id",
		"`tweet_factory`.`status`" => "status",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`tweet_factory` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tweet_factory_view.php';
	$x->TableTitle = 'Tweet_factory';
	$x->TableIcon = 'resources/table_icons/factory.png';
	$x->PrimaryKey = '`tweet_factory`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Logo', 'File_path', 'Execution', 'Automation', 'Category', 'Title', 'Description', 'Author', 'User_id', 'Status', ];
	$x->ColFieldName = ['id', 'logo', 'file_path', 'execution', 'automation', 'category', 'title', 'description', 'author', 'user_id', 'status', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tweet_factory_templateTV.html';
	$x->SelectedTemplate = 'templates/tweet_factory_templateTVS.html';
	$x->TemplateDV = 'templates/tweet_factory_templateDV.html';
	$x->TemplateDVP = 'templates/tweet_factory_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tweet_factory_init
	$render = true;
	if(function_exists('tweet_factory_init')) {
		$args = [];
		$render = tweet_factory_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tweet_factory_header
	$headerCode = '';
	if(function_exists('tweet_factory_header')) {
		$args = [];
		$headerCode = tweet_factory_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tweet_factory_footer
	$footerCode = '';
	if(function_exists('tweet_factory_footer')) {
		$args = [];
		$footerCode = tweet_factory_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
