<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/usage_track.php');
	include_once(__DIR__ . '/usage_track_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('usage_track');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'usage_track';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`usage_track`.`id`" => "id",
		"`usage_track`.`time`" => "time",
		"`usage_track`.`points`" => "points",
		"`usage_track`.`user_id`" => "user_id",
		"`usage_track`.`action`" => "action",
		"`usage_track`.`consumer_key`" => "consumer_key",
		"`usage_track`.`level`" => "level",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`usage_track`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`usage_track`.`id`" => "id",
		"`usage_track`.`time`" => "time",
		"`usage_track`.`points`" => "points",
		"`usage_track`.`user_id`" => "user_id",
		"`usage_track`.`action`" => "action",
		"`usage_track`.`consumer_key`" => "consumer_key",
		"`usage_track`.`level`" => "level",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`usage_track`.`id`" => "Id",
		"`usage_track`.`time`" => "Time",
		"`usage_track`.`points`" => "Points",
		"`usage_track`.`user_id`" => "User_id",
		"`usage_track`.`action`" => "Action",
		"`usage_track`.`consumer_key`" => "Consumer_key",
		"`usage_track`.`level`" => "Level",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`usage_track`.`id`" => "id",
		"`usage_track`.`time`" => "time",
		"`usage_track`.`points`" => "points",
		"`usage_track`.`user_id`" => "user_id",
		"`usage_track`.`action`" => "action",
		"`usage_track`.`consumer_key`" => "consumer_key",
		"`usage_track`.`level`" => "level",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`usage_track` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'usage_track_view.php';
	$x->TableTitle = 'Usage_track';
	$x->TableIcon = 'resources/table_icons/routing_turn_left_crossroads.png';
	$x->PrimaryKey = '`usage_track`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Time', 'Points', 'User_id', 'Action', 'Consumer_key', 'Level', ];
	$x->ColFieldName = ['id', 'time', 'points', 'user_id', 'action', 'consumer_key', 'level', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/usage_track_templateTV.html';
	$x->SelectedTemplate = 'templates/usage_track_templateTVS.html';
	$x->TemplateDV = 'templates/usage_track_templateDV.html';
	$x->TemplateDVP = 'templates/usage_track_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: usage_track_init
	$render = true;
	if(function_exists('usage_track_init')) {
		$args = [];
		$render = usage_track_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: usage_track_header
	$headerCode = '';
	if(function_exists('usage_track_header')) {
		$args = [];
		$headerCode = usage_track_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: usage_track_footer
	$footerCode = '';
	if(function_exists('usage_track_footer')) {
		$args = [];
		$footerCode = usage_track_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
