<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/users.php');
	include_once(__DIR__ . '/users_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('users');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'users';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`users`.`id`" => "id",
		"`users`.`email`" => "email",
		"`users`.`password`" => "password",
		"`users`.`type`" => "type",
		"`users`.`firstname`" => "firstname",
		"`users`.`lastname`" => "lastname",
		"`users`.`username`" => "username",
		"`users`.`address`" => "address",
		"`users`.`country`" => "country",
		"`users`.`contact_info`" => "contact_info",
		"`users`.`contact_verify`" => "contact_verify",
		"`users`.`photo`" => "photo",
		"`users`.`status`" => "status",
		"`users`.`activate_code`" => "activate_code",
		"`users`.`reset_code`" => "reset_code",
		"`users`.`created_on`" => "created_on",
		"`users`.`source`" => "source",
		"`users`.`verified`" => "verified",
		"`users`.`occupation`" => "occupation",
		"`users`.`company`" => "company",
		"`users`.`company_site`" => "company_site",
		"`users`.`language`" => "language",
		"`users`.`time_zone`" => "time_zone",
		"`users`.`currency`" => "currency",
		"`users`.`email_comm`" => "email_comm",
		"`users`.`phone_comm`" => "phone_comm",
		"`users`.`marketing`" => "marketing",
		"`users`.`two_auth`" => "two_auth",
		"`users`.`two_auth_secret`" => "two_auth_secret",
		"`users`.`g_id`" => "g_id",
		"`users`.`f_id`" => "f_id",
		"`users`.`t_id`" => "t_id",
		"`users`.`access_token`" => "access_token",
		"`users`.`access_secret`" => "access_secret",
		"`users`.`p_value`" => "p_value",
		"`users`.`p_key`" => "p_key",
		"`users`.`p_cipher`" => "p_cipher",
		"`users`.`referer_code`" => "referer_code",
		"`users`.`referer_id`" => "referer_id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`users`.`id`',
		2 => 2,
		3 => 3,
		4 => '`users`.`type`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => '`users`.`contact_verify`',
		12 => 12,
		13 => '`users`.`status`',
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => '`users`.`email_comm`',
		26 => '`users`.`phone_comm`',
		27 => '`users`.`marketing`',
		28 => '`users`.`two_auth`',
		29 => 29,
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => 34,
		35 => 35,
		36 => 36,
		37 => 37,
		38 => 38,
		39 => 39,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`users`.`id`" => "id",
		"`users`.`email`" => "email",
		"`users`.`password`" => "password",
		"`users`.`type`" => "type",
		"`users`.`firstname`" => "firstname",
		"`users`.`lastname`" => "lastname",
		"`users`.`username`" => "username",
		"`users`.`address`" => "address",
		"`users`.`country`" => "country",
		"`users`.`contact_info`" => "contact_info",
		"`users`.`contact_verify`" => "contact_verify",
		"`users`.`photo`" => "photo",
		"`users`.`status`" => "status",
		"`users`.`activate_code`" => "activate_code",
		"`users`.`reset_code`" => "reset_code",
		"`users`.`created_on`" => "created_on",
		"`users`.`source`" => "source",
		"`users`.`verified`" => "verified",
		"`users`.`occupation`" => "occupation",
		"`users`.`company`" => "company",
		"`users`.`company_site`" => "company_site",
		"`users`.`language`" => "language",
		"`users`.`time_zone`" => "time_zone",
		"`users`.`currency`" => "currency",
		"`users`.`email_comm`" => "email_comm",
		"`users`.`phone_comm`" => "phone_comm",
		"`users`.`marketing`" => "marketing",
		"`users`.`two_auth`" => "two_auth",
		"`users`.`two_auth_secret`" => "two_auth_secret",
		"`users`.`g_id`" => "g_id",
		"`users`.`f_id`" => "f_id",
		"`users`.`t_id`" => "t_id",
		"`users`.`access_token`" => "access_token",
		"`users`.`access_secret`" => "access_secret",
		"`users`.`p_value`" => "p_value",
		"`users`.`p_key`" => "p_key",
		"`users`.`p_cipher`" => "p_cipher",
		"`users`.`referer_code`" => "referer_code",
		"`users`.`referer_id`" => "referer_id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`users`.`id`" => "Id",
		"`users`.`email`" => "Email",
		"`users`.`password`" => "Password",
		"`users`.`type`" => "Type",
		"`users`.`firstname`" => "Firstname",
		"`users`.`lastname`" => "Lastname",
		"`users`.`username`" => "Username",
		"`users`.`address`" => "Address",
		"`users`.`country`" => "Country",
		"`users`.`contact_info`" => "Contact_info",
		"`users`.`contact_verify`" => "Contact_verify",
		"`users`.`photo`" => "Photo",
		"`users`.`status`" => "Status",
		"`users`.`activate_code`" => "Activate_code",
		"`users`.`reset_code`" => "Reset_code",
		"`users`.`created_on`" => "Created_on",
		"`users`.`source`" => "Source",
		"`users`.`verified`" => "Verified",
		"`users`.`occupation`" => "Occupation",
		"`users`.`company`" => "Company",
		"`users`.`company_site`" => "Company_site",
		"`users`.`language`" => "Language",
		"`users`.`time_zone`" => "Time_zone",
		"`users`.`currency`" => "Currency",
		"`users`.`email_comm`" => "Email_comm",
		"`users`.`phone_comm`" => "Phone_comm",
		"`users`.`marketing`" => "Marketing",
		"`users`.`two_auth`" => "Two_auth",
		"`users`.`two_auth_secret`" => "Two_auth_secret",
		"`users`.`g_id`" => "G_id",
		"`users`.`f_id`" => "F_id",
		"`users`.`t_id`" => "T_id",
		"`users`.`access_token`" => "Access_token",
		"`users`.`access_secret`" => "Access_secret",
		"`users`.`p_value`" => "P_value",
		"`users`.`p_key`" => "P_key",
		"`users`.`p_cipher`" => "P_cipher",
		"`users`.`referer_code`" => "Referer_code",
		"`users`.`referer_id`" => "Referer_id",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`users`.`id`" => "id",
		"`users`.`email`" => "email",
		"`users`.`password`" => "password",
		"`users`.`type`" => "type",
		"`users`.`firstname`" => "firstname",
		"`users`.`lastname`" => "lastname",
		"`users`.`username`" => "username",
		"`users`.`address`" => "address",
		"`users`.`country`" => "country",
		"`users`.`contact_info`" => "contact_info",
		"`users`.`contact_verify`" => "contact_verify",
		"`users`.`photo`" => "photo",
		"`users`.`status`" => "status",
		"`users`.`activate_code`" => "activate_code",
		"`users`.`reset_code`" => "reset_code",
		"`users`.`created_on`" => "created_on",
		"`users`.`source`" => "source",
		"`users`.`verified`" => "verified",
		"`users`.`occupation`" => "occupation",
		"`users`.`company`" => "company",
		"`users`.`company_site`" => "company_site",
		"`users`.`language`" => "language",
		"`users`.`time_zone`" => "time_zone",
		"`users`.`currency`" => "currency",
		"`users`.`email_comm`" => "email_comm",
		"`users`.`phone_comm`" => "phone_comm",
		"`users`.`marketing`" => "marketing",
		"`users`.`two_auth`" => "two_auth",
		"`users`.`two_auth_secret`" => "two_auth_secret",
		"`users`.`g_id`" => "g_id",
		"`users`.`f_id`" => "f_id",
		"`users`.`t_id`" => "t_id",
		"`users`.`access_token`" => "access_token",
		"`users`.`access_secret`" => "access_secret",
		"`users`.`p_value`" => "p_value",
		"`users`.`p_key`" => "p_key",
		"`users`.`p_cipher`" => "p_cipher",
		"`users`.`referer_code`" => "referer_code",
		"`users`.`referer_id`" => "referer_id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`users` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'users_view.php';
	$x->TableTitle = 'Users';
	$x->TableIcon = 'resources/table_icons/drive_user.png';
	$x->PrimaryKey = '`users`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Email', 'Password', 'Type', 'Firstname', 'Lastname', 'Username', 'Address', 'Country', 'Contact_info', 'Contact_verify', 'Photo', 'Status', 'Activate_code', 'Reset_code', 'Created_on', 'Source', 'Verified', 'Occupation', 'Company', 'Company_site', 'Language', 'Time_zone', 'Currency', 'Email_comm', 'Phone_comm', 'Marketing', 'Two_auth', 'Two_auth_secret', 'G_id', 'F_id', 'T_id', 'Access_token', 'Access_secret', 'P_value', 'P_key', 'P_cipher', 'Referer_code', 'Referer_id', ];
	$x->ColFieldName = ['id', 'email', 'password', 'type', 'firstname', 'lastname', 'username', 'address', 'country', 'contact_info', 'contact_verify', 'photo', 'status', 'activate_code', 'reset_code', 'created_on', 'source', 'verified', 'occupation', 'company', 'company_site', 'language', 'time_zone', 'currency', 'email_comm', 'phone_comm', 'marketing', 'two_auth', 'two_auth_secret', 'g_id', 'f_id', 't_id', 'access_token', 'access_secret', 'p_value', 'p_key', 'p_cipher', 'referer_code', 'referer_id', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/users_templateTV.html';
	$x->SelectedTemplate = 'templates/users_templateTVS.html';
	$x->TemplateDV = 'templates/users_templateDV.html';
	$x->TemplateDVP = 'templates/users_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: users_init
	$render = true;
	if(function_exists('users_init')) {
		$args = [];
		$render = users_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: users_header
	$headerCode = '';
	if(function_exists('users_header')) {
		$args = [];
		$headerCode = users_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: users_footer
	$footerCode = '';
	if(function_exists('users_footer')) {
		$args = [];
		$footerCode = users_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
