<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/user_earnings.php');
	include_once(__DIR__ . '/user_earnings_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('user_earnings');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'user_earnings';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`user_earnings`.`id`" => "id",
		"`user_earnings`.`user_id`" => "user_id",
		"`user_earnings`.`app`" => "app",
		"`user_earnings`.`refer`" => "refer",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`user_earnings`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`user_earnings`.`id`" => "id",
		"`user_earnings`.`user_id`" => "user_id",
		"`user_earnings`.`app`" => "app",
		"`user_earnings`.`refer`" => "refer",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`user_earnings`.`id`" => "Id",
		"`user_earnings`.`user_id`" => "User_id",
		"`user_earnings`.`app`" => "App",
		"`user_earnings`.`refer`" => "Refer",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`user_earnings`.`id`" => "id",
		"`user_earnings`.`user_id`" => "user_id",
		"`user_earnings`.`app`" => "app",
		"`user_earnings`.`refer`" => "refer",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`user_earnings` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'user_earnings_view.php';
	$x->TableTitle = 'User_earnings';
	$x->TableIcon = 'resources/table_icons/cash_terminal.png';
	$x->PrimaryKey = '`user_earnings`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'User_id', 'App', 'Refer', ];
	$x->ColFieldName = ['id', 'user_id', 'app', 'refer', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/user_earnings_templateTV.html';
	$x->SelectedTemplate = 'templates/user_earnings_templateTVS.html';
	$x->TemplateDV = 'templates/user_earnings_templateDV.html';
	$x->TemplateDVP = 'templates/user_earnings_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: user_earnings_init
	$render = true;
	if(function_exists('user_earnings_init')) {
		$args = [];
		$render = user_earnings_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: user_earnings_header
	$headerCode = '';
	if(function_exists('user_earnings_header')) {
		$args = [];
		$headerCode = user_earnings_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: user_earnings_footer
	$footerCode = '';
	if(function_exists('user_earnings_footer')) {
		$args = [];
		$footerCode = user_earnings_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
